### ISSUE TITLE
Breaking change: Original escape sequent converted 

### ISSUE THREAD

**Issue by willworkforhugs** [javascript-obfuscator/javascript-obfuscator#747] opened 2020-09-15 22:23 UTC
Unless I turn on the unicodeEscapeSequence flag (which makes the output much larger), the following code will break: 

`textContent += '\0';`

The issue is that the '\0' won't be left alone. This is required for my code to work and it is converted to the equivalent Unicode null value, when then creates JS that won't parse correctly. Is there no flag to prevent conversion of escaped sequences to preserve the original?

Broken output looks like:
_0x4ad68d += '';

**Comment by sanex3339** [comment] 2020-09-16 02:21
Hi. If you need to keep the original string, use conditional comments

**Comment by sanex3339** [comment] 2020-09-16 06:12
Can you make a small example that shows a bug?

**Comment by sanex3339** [comment] 2020-09-16 06:16
Cannot reproduce.
My example:

Input:
```
let textContent = '\8 ';
textContent += '\8';

console.log(textContent);
```

Output:
```
let textContent = '8\x20';
textContent += '8';
console['log'](textContent);
// Outputa `8 8`
```

**Comment by sanex3339** [comment] 2020-09-16 06:17
So i need an example and more details: obfuscator version and used options.

**Comment by willworkforhugs** [comment] 2020-09-16 14:45
Thank you for your quick response!

Here's a more complete example that demonstrates the issue:

```
function addDiv(target) {
    let textContent = 'simple message'
    textContent += '\0'; 
    const newElement = document.createElement('div');
    newElement.textContent = textContent;
    return target.appendChild(newElement);
}
```

becomes:
```
const _0x1dac = [
    'div',
    'createElement',
    'gbnzVJS475'
];
(function (_0x431376, _0x1daccc) {
    const _0x501278 = function (_0x56a57f) {
        while (--_0x56a57f) {
            _0x431376['push'](_0x431376['shift']());
        }
    };
    _0x501278(++_0x1daccc);
}(_0x1dac, 0x10b));
const _0x5012 = function (_0x431376, _0x1daccc) {
    _0x431376 = _0x431376 - 0x0;
    let _0x501278 = _0x1dac[_0x431376];
    return _0x501278;
};
function gbnzFJS20(_0x56a57f) {
    const _0x280340 = _0x5012;
    let _0x1b0575 = 'simple\x20message';
    **_0x1b0575 += '

**Comment by willworkforhugs** [comment] 2020-09-16 15:02
becomes:
```
...
function addDiv(_0x17a116) {
    const _0x11be3a = _0x8d5d;
    let _0x413c0c = _0x11be3a('0x1');
    _0x413c0c += '

**Comment by willworkforhugs** [comment] 2020-09-16 15:03
using:
```
let options = {};
  options.compact = false;
  options.unicodeEscapeSequence = false;

gulp
	.src(parentFolder + "**/*.js")
	.pipe(javascriptObfuscator(options))
	.pipe(gulp.dest(parentFolder))
```

**Comment by sanex3339** [comment] 2020-09-17 09:40
Ok, I see the problem

**Comment by sanex3339** [comment] 2020-09-17 09:45
Or not. It' strange. For me seems it works fine.

**Comment by sanex3339** [comment] 2020-09-17 09:47
Looks like the obfuscator itself works fine and produces a code with correct characters. But this `nul` character is removed after you copy-paste this file.

**Comment by sanex3339** [comment] 2020-09-17 09:54
So, the code:
```
function addDiv(target) {
    let textContent = 'simple message'
    textContent += '\0abc';
    const newElement = document.createElement('div');
    newElement.textContent = textContent.split('\0')[0];
    target.appendChild(newElement);
}
addDiv(document.body);
```

Works fine after obfuscation and displays only `simple message` string.
But IF I copy this obfuscated code from `obfuscator.io` site - after pasting it does not contain the `nul` characters and outputs looks like `s`.

**Comment by sanex3339** [comment] 2020-09-17 09:55
So my question is - are you copy a content of the obfuscated file after obfuscation?

**Comment by willworkforhugs** [comment] 2020-09-17 14:11
I know it sounds strange, but I actually need to use just that single character. And while the output is a valid interpretation of \0, the Chrome V8 engine will not parse it. So it is a breaking change. It is not a matter of copy and paste, I am using Gulp and the output fails to parse in Chrome.

That character is fine in other contexts. VSCode seems to respect it and shows that funny diamond with a question mark character. But it is not a universally accepted character, which is why I'm using an escape sequence there.

Is there no way to prevent the obfuscator from leaving escaped sequences alone?

**Comment by willworkforhugs** [comment] 2020-09-17 14:18
As a workaround, I can use this instead: String.fromCharCode(0)

However, it would seem like the obfuscator should not converted escaped sequences or at least not that particular one and offer an option if it is going to change it.

**Comment by sanex3339** [comment] 2020-09-17 14:20
For me chrome parses it correctly

**Comment by willworkforhugs** [comment] 2020-09-17 14:24
I'm using the V8 engine in a separate instance outside the Chrome browser. It is failing on that specific character in my testing. The error message is unambiguous, console logging of the error cuts off right at that character.

**Comment by sanex3339** [comment] 2020-09-17 15:45
Ok. I will add force convert of the Unicode control characters to the escape sequence

**Comment by sanex3339** [comment] 2020-09-17 16:04
PR: https://github.com/javascript-obfuscator/javascript-obfuscator/pull/750

**Comment by sanex3339** [comment] 2020-09-17 17:24
Merged into `master`. Please try it directly from the `master` branch and say if your problem was resolved.

**Comment by willworkforhugs** [comment] 2020-09-17 17:43
Happy to test. Unfortunately, I'm a bit thick on github. Is there an updated version for npm or https://obfuscator.io/ where I can try it? If npm for gulp, what's the required options property to set?

**Comment by sanex3339** [comment] 2020-09-17 17:47
You can install it as a dependency directly from github branch:
```
"javascript-obfuscator": "git+https://github.com/javascript-obfuscator/javascript-obfuscator.git"
```

If you're using yarn, you can use `resolutions` section to temporary override `javascript-obfuscator` version for some other package, for example for `webpack-obfuscator`.

**Comment by sanex3339** [comment] 2020-09-17 17:57
Ok. I'll release a new version of `javascript-obfuscator` in a few minutes.

**Comment by sanex3339** [comment] 2020-09-17 18:01
Released as `2.3.0`

**Closed** 2020-09-17 18:02 UTC
Labels: enhancement, need more info, waiting for release

**Comment by willworkforhugs** [comment] 2020-09-17 18:34
Works great! I'm seeing my '\0' replaced with '\x00' in the output and it parses just fine.  Thank you!

**Comment by sanex3339** [comment] 2020-09-17 18:35
Nice!

**Comment by sanex3339** [comment] 2020-09-17 19:18
Also i updated https://obfuscator.io/

**Comment by willworkforhugs** [comment] 2020-09-17 19:21
Great! By the way, I tested with Gulp. Had to force the update of the dependency, but works with the new version 2.3.0.
