### ISSUE TITLE
[Feature Request] Expire Time

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#737] opened 2020-09-07 09:05 UTC
**Description**
I want to ask feature what stop run code when obfuscatedobfuscate code is expire.

**Describe the solution you'd like**

I think in settings you can add parameter like `expireTime: (time in seconds or hours or days etc`.

This add a block of code what check current time and expire time.

If current time >= expire time - stop run code.

**Comment by sanex3339** [comment] 2020-09-07 09:10
Duplicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/105
Not in the nearest plans.

**Closed by sanex3339** 2020-09-07 09:10 UTC

**Comment by da411d** [comment] 2020-09-14 13:24
@BlackYuzia if it is urgent, you can just implement your own protection in your code. Check out my comment here [issues/385#issuecomment-652669312](https://github.com/javascript-obfuscator/javascript-obfuscator/issues/385#issuecomment-652669312)

**Comment by sanex3339** [comment] 2020-09-14 13:26
Just to be clear: the current focus is to make more complicated transformations of the code itself.
All stuff that's related to some additional code helpers like `dateLock` and other stuff - very far plans.
