### ISSUE TITLE
problem with file paths

### ISSUE THREAD

**Issue by mo-js** [javascript-obfuscator/javascript-obfuscator#57] opened 2017-06-18 13:32 UTC
i am using javascript obfuscator with angular 2 and sytemjs for electron application.
the problem is after obfuscation file paths are wrong and systemjs get file not found error.
for example:
`Object['defineProperty'](exports, '\x5f\x5fesModule', { '\x76\x61\x6c\x75\x65': !![] });
var core_1 = require('\x40angular\x2fcore');
var router_1 = require('\x40angular\x2frouter');`

**Comment by sanex3339** [comment] 2017-06-18 13:34
Hmm strange, path like `require('\x40angular\x2fcore');` should be a valid file path.
Can you provide small example app with this problem?

**Comment by mo-js** [comment] 2017-06-18 13:47
when i run electron app on windows the final path is like
`D:/appfolder/dist/x40angular/x2fplatform/x2dbrowser`
but folder names are:
`D:/appfolder/dist/@angular/platform-browser`

**Comment by sanex3339** [comment] 2017-06-18 14:22
Path like `x40angular/x2fplatform` should be understanded by javascript engine like usual `@angular/platform-browser` path.

But in your example here strange problem with escape slashes and hyphen.
Can you provide small example with one or two files that i can reproduce this error?

**Comment by sanex3339** [comment] 2017-06-18 14:27
For example

```
var _0x6051 = ['\x40angular\x2frouter'];
var _0x1605 = function (_0x41af57, _0x9291fc) {
    _0x41af57 = _0x41af57 - 0x0;
    var _0x51c5de = _0x6051[_0x41af57];
    return _0x51c5de;
};
var module = require(_0x1605('0x0'));
```

With this code i got error: `Cannot find module '@angular/router'` because i haven't this module.

**Comment by mo-js** [comment] 2017-06-18 14:44
i think systemjs is the problem.
when module name has any of (@ . - /) in form of hex (\x40 \x2e \x2d \x2f ) systemjs cannot load the module.
is there any way to prevent hex encoding for "require"?

**Comment by sanex3339** [comment] 2017-06-18 14:45
Right now - no. I'll look into this.

**Comment by mo-js** [comment] 2017-06-19 07:01
for now i tried to replace back hex for (\x40 \x2e \x2d \x2f) after obfuscation and it's ok!
we may report this problem to systemjs.
thanks for your project and your support.

**Comment by sanex3339** [comment] 2017-06-19 08:35
From my side currently even if 'unicodeEscapeSequence' option is disabled - all non-digit and non-latin symbols will encoded to unicode escape sequence. 

This is hack because without that i got `esprima` errors like `unexpected token ILLEGAL`. 
Now i should understand why this errors happens and encode or escape only important characters, so i'll work on this today and this fix shold be as part of `0.9.5` version alongside with `es2017` async functions support.

**Comment by sanex3339** [comment] 2017-06-19 22:12
Hi again!
Please try new `javascript-obfuscator@0.10.0-beta.4`

**Comment by sanex3339** [comment] 2017-07-03 12:08
Any news?

**Comment by sanex3339** [comment] 2017-07-10 21:13
Problem should be fixed few beta releases ago. Closed.

**Closed by sanex3339** 2017-07-10 21:13 UTC
Labels: high priority, need more info
