### ISSUE TITLE
Incorrect output when escaping quotes

### ISSUE THREAD

**Issue by getkey** [javascript-obfuscator/javascript-obfuscator#340] opened 2018-10-10 17:20 UTC
## Expected Behavior

Output should be:

```js
// code1
console['info']('Map does not exist! Defaulting to '+defaultMapName);
// code 2
throw new Error('Attempting to add a delete button but the previous one hasn\'t been removed');
```

## Current Behavior

Output is:
```js
// code1
console['info']('Map does not exist! Defaulting to ''+defaultMapName+''');
// code2
throw new Error('Attempting to add a delete button but the previous one hasn't been removed');
```

Which obviously is incorrect JavaScript and won't run.

## Steps to Reproduce (for bugs)

Here is my minimum working example. Just run it and compare the output.

```js
const obfuscator = require('javascript-obfuscator');

const code1 = "console.info(`Map does not exist! Defaulting to '${defaultMapName}'`);";
const code2 = "throw new Error('Attempting to add a delete button but the previous one hasn\\'t been removed');" // please also try with this string

const obfuscationResult = obfuscator.obfuscate(code1, {
	reservedNames: [
		'.',
	],
	reservedStrings: [
		'.'
	],
});
const output = obfuscationResult.getObfuscatedCode();
console.log(output);
```

## Your Environment

* Obfuscator version used: 0.8.1
* Node version used: 8.11.3

Thanks for the lib, it's some great work! 😄

**Comment by zamotkin** [comment] 2019-11-28 19:28
Cannot reproduce in 0.18.4.

**Comment by zamotkin** [comment] 2019-11-30 16:43
@getkey closing your issue, please feel free to re-open it if the problem have not solved yet.

**Closed** 2019-11-30 16:43 UTC
