### ISSUE TITLE
Obfuscator breaks code that uses object destructuring

### ISSUE THREAD

**Issue by bfree-bellus3d** [javascript-obfuscator/javascript-obfuscator#421] opened 2019-10-11 22:44 UTC
Object destructuring results in undefined variables:

const {a, b} = {a:'test', b:'me'};
console.log(a, b);
// a and b are undefined after obfuscation

I suspect that the obfuscator sees the curly braces and assumes the scope is limited to within them, and become out of scope outside the braces.  I don't have time to fix at the moment.

If someone else doesn't get to it first, I may be able to work on it in a few months.

## Expected Behavior

Destructuring has been supported since ECMA 6.

The expectation is that the above code will work after obfuscation, as it does before.

## Current Behavior

The assigned variables are undefined.

## Steps to Reproduce (for bugs)

const {a, b} = {a:'test', b:'me'};
console.log(a, b);
// a and b are undefined after obfuscation

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 10.16

# Stack trace

## Minimal working example that will help to reproduce issue

const {a, b} = {a:'test', b:'me'};
console.log(a, b);
// a and b are undefined after obfuscation

**Comment by JustAnotherGitHubUserYouDontKnow** [comment] 2019-10-12 11:26
I worried about this when I read it, as I use destructured assignment frequently, though I hadn't experienced any issues.

So, I tried this explicit example with obfuscator version 0.18.1 and node version 8.12.0 and had no such problem. I used default options.

My obfuscated output code is:

var _0x3b99=['test'];(function(_0x1c5671,_0x53836d){var _0x423ee2=function(_0x5827da){while(--_0x5827da){_0x1c5671['push'](_0x1c5671['shift']());}};_0x423ee2(++_0x53836d);}(_0x3b99,0x1d5));var _0x2b39=function(_0x2d0352,_0x25f66b){_0x2d0352=_0x2d0352-0x0;var _0x3fc428=_0x3b99[_0x2d0352];return _0x3fc428;};const {a,b}={'a':_0x2b39('0x0'),'b':'me'};console['log'](a,b);

It runs without issue within node, outputting 'test me' as expected.

Sorry, I know that's little help for you, but perhaps reassuring for others. Good luck in hunting down your issue.

**Comment by zamotkin** [comment] 2019-11-30 18:49
Can't reproduce, closing.

**Closed by zamotkin** 2019-11-30 18:49 UTC
