### ISSUE TITLE
BUG: Online Obfuscator Tool not working properly

### ISSUE THREAD

**Issue by shelleyvs** [javascript-obfuscator/javascript-obfuscator#258] opened 2018-05-10 10:10 UTC
Seems like something is seriously wrong with your online obfuscator. We cant test any other code, nor add self-defending, domain lock etc..etc...The default code works. If we change the code we cant enter anything in domain lock etc. Unusable. Not working in Firefox & Chrome.
https://obfuscator.io/

**Comment by shelleyvs** [comment] 2018-05-10 10:11
Same issue at:
https://javascriptobfuscator.herokuapp.com

**Comment by sanex3339** [comment] 2018-05-10 10:13
Can you record a video? Can't reproduce

**Comment by sanex3339** [comment] 2018-05-10 10:26
Everything is ok. Please, record a video.

**Comment by shelleyvs** [comment] 2018-05-10 10:28
[https://youtu.be/B83ohe_ZvCI](Video)

**Comment by shelleyvs** [comment] 2018-05-10 10:32
Tested with:
Firefox Developer Edition: 61.0b3 (64-bit)
Firefox Quantum 59.0.2 (64-bit)
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
OS - Linux Mint Mate

In all these browsers it is not working.

**Comment by shelleyvs** [comment] 2018-05-10 10:35
With the default code, it is okay. Enter any other code and try to enter domain lock. It will not work.

**Comment by wse-ltd** [comment] 2018-05-10 10:59
I concur.  You copy and paste the text. It kind of scrolls up and then does nothing. Also the file upload isn't working.

**Comment by sanex3339** [comment] 2018-05-10 11:10
File upload not working, yes. 
About vibrating - can't reproduce.
But i noticed that for some reason sometimes after obfuscation textarea with result is empty.

**Comment by wse-ltd** [comment] 2018-05-10 11:15
Works in MS Edge: 41.16299.402.0

**Comment by shelleyvs** [comment] 2018-05-11 08:55
When will this be resolved ??

**Comment by sanex3339** [comment] 2018-05-11 08:55
When i will have a time

**Comment by sanex3339** [comment] 2018-05-11 10:12
File upload should work now

**Comment by sanex3339** [comment] 2018-05-11 12:01
About vibrating - attach video, please. Without it i can't help.

**Comment by shelleyvs** [comment] 2018-05-11 12:35
I just tested again with all browsers, including Opera 53.0.2907.37. Nothing can't be entered into the text area. If we type something in domain lock, it will appear in the text area. Unusable. By vibration i mean the flicker in text area if we try to enter something. 

Not tested file upload.

**Comment by sanex3339** [comment] 2018-05-11 12:37
Please record the video.

**Comment by sanex3339** [comment] 2018-05-11 12:38
Reproduced now. Will look into that.

**Comment by shelleyvs** [comment] 2018-05-11 12:43
Here is the video:
https://youtu.be/RoG54ghm_vw

**Comment by Pamela-UK** [comment] 2018-05-12 17:13
Yep! This is not working in any browser. Hope it will be corrected soon.

**Comment by sanex3339** [comment] 2018-05-12 20:41
Problem is that i can't reproduce it locally, only after deploy.

**Comment by shelleyvs** [comment] 2018-05-13 06:36
I am willing to assist you.

**Comment by sanex3339** [comment] 2018-05-13 11:46
Please, check now

**Comment by shelleyvs** [comment] 2018-05-13 16:46
Yes. The WebUI issue seems resolved when i checked. Let somebody else test it too.

**Comment by sanex3339** [comment] 2018-05-13 17:46
Nice! I will close this issue. Reopen it if problem will happen again

**Closed by sanex3339** 2018-05-13 17:46 UTC
Labels: Web UI, bug, help wanted, high priority, need more info

**Comment by ks1505** [comment] 2019-07-14 14:55
Domain lock is still not working
