### ISSUE TITLE
Avast

### ISSUE THREAD

**Issue by ibmua** [javascript-obfuscator/javascript-obfuscator#51] opened 2017-05-07 17:14 UTC
I'm getting Avast antivirus detecting my script as false positive virus threat.

my config used to be:

```
      	rotateUnicodeArray: true
		,
	compact: true,
	controlFlowFlattening: false,
	deadCodeInjection: false,
	debugProtection: false,
	debugProtectionInterval: false,
	disableConsoleOutput: true,
	rotateStringArray: true,
	selfDefending: true,
	stringArray: true,
	stringArrayEncoding: 'base64',
	stringArrayThreshold: 0.75,
	unicodeEscapeSequence: false

```

I also tried "lowest" settings, but it still detected as false positive. Forgone the obfuscation altogether and it stopped complaining.

**Comment by sanex3339** [comment] 2017-05-08 07:49
It's bad. In a few days i'll try to contact with Avast and describe this problem.

Can you attach working sample with obfuscated code that trigger Avast antivirus?
I'll attach this code to this page
https://www.avast.ru/false-positive-file-form.php

**Comment by ibmua** [comment] 2017-05-08 12:47
http://fsymbols.com/tell/main.fda15551.js

**Comment by ibmua** [comment] 2017-05-08 13:55
Mind that it is highly unlikely that it only has to do with Avast. I'm guessing that many more antiviruses see that code as a threat. It's just that I only tried on Avast.

**Comment by sanex3339** [comment] 2017-05-11 19:00
How i can reproduce this on Mac? It's Avast extension for browser?

Can you try to run Uglify.js over obfuscated code and check with Avast again? Still detecting as virus threat?

**Comment by sanex3339** [comment] 2017-05-11 19:22
Got it on your file with https://www.virustotal.com/ru/ 
Currently only one or two antiviruses detecting this code as threat.

**Comment by sanex3339** [comment] 2017-05-11 19:54
Please try to run Uglify.js over obfuscated code or try latest beta with `mangle: true` option

**Comment by ibmua** [comment] 2017-05-15 23:37
Of course, the result isn't any different than it would be if you ran Uglify over that script. Ran it uglified on VirusTotal and got a 
`NANO-Antivirus	Trojan.Script.Agent.enqons	
`
detection https://www.virustotal.com/ru/file/f31dfbb30d1536fff0b6f6701c705ea4b2111bfc7e79cb6bd587b93681f7f8bf/analysis/1494891276/

**Comment by NeXTs** [comment] 2017-06-12 19:03
same here 😞

**Comment by sanex3339** [comment] 2017-06-12 19:57
I should make research. if anyone have information - why few antiviruses mark obfuscated code as threat - i will very happy.

**Comment by NeXTs** [comment] 2017-07-17 07:56
@sanex3339 
Hey Timofey, have you contacted Avast?

Actually this issue is critical blocker for production use :/

**Comment by sanex3339** [comment] 2017-07-17 08:04
Hi, no. But please try to use latest beta: 0.10.0-beta.8.
I removed all `eval`s from obfuscated code, so maybe it won't detect your script as the virus threat.

**Comment by sanex3339** [comment] 2017-07-30 09:34
Hi. Please try new `0.10.0` version. Avast still triggering on your code?

**Comment by sanex3339** [comment] 2017-07-31 20:53
ping

**Comment by ibmua** [comment] 2017-07-31 23:26
My code's changed a bit, but if it still has the same features that brought up the warnings you can experiment converting http://fsymbols.com/tell/main.a51a389b.js at any time with settings you're interested about and checking with VT to see how the antiviruses react. No need for waiting. 

If this code doesn't trigger errors even with an earlier obfuscatior, I'll try to find you an earlier version that may.

**Comment by sanex3339** [comment] 2017-08-05 10:56
Hi. After some tests i noticed that `Avast` triggered when string literals are moving to the string array from objects keys that had `computed` property with `false` value.

Obfuscator transforming object keys:
```
var foo = {
    bar: 'baz'
};
```

into this form:
```
var foo = {
    'bar': 'baz'
};
```

And then moving this string literal 'bar' to the string array.
So, on your code after moving object keys to string array - avast will detect your code as the threat.

Solution - enable `stringArrayEncoding: 'base64'`
With this option enabled - all antivirus checks are passed on file that you sent in previous message. Tested on `0.10.2` version

**Comment by sanex3339** [comment] 2017-08-19 11:09
Ping. Any news?

**Comment by ibmua** [comment] 2017-08-19 17:34
No news here. =)

**Comment by NeXTs** [comment] 2017-08-21 09:11
Hey, sorry for long silence from my side. I haven't tested new release on production since we've refused obfuscation on production because of complaints from users about antivirus notification. This was critical for our product. Anyway I'll try to find a minute to test it on stage server in nearest days.

**Comment by sanex3339** [comment] 2017-12-17 22:29
Please, check `0.13.0` version with `hexadecimal` and `mangled` values of `identifierNamesGenerator` option.

**Comment by sanex3339** [comment] 2018-01-01 14:50
ping

**Comment by sanex3339** [comment] 2018-01-01 15:26
Tested it now with command 
`javascript-obfuscator test.js --identifier-names-generator mangled --compact true --disable-console-output true --self-defending true --dead-code-injection true --control-flow-flattening true
`

No false positive alerts. 
https://www.virustotal.com/ru/file/53af005143ac8cfd2eea82c0d05ba2ccf77d2ddd49182aa37632f42dfdec89c9/analysis/1514820105/

But enabling of `stringArrayEncoding: base64` will trigger false positive alert. 
So current status - if you will got this error - try to play with `stringArrayEncoding` option and disable it or change it on `rc4`.

**Comment by sanex3339** [comment] 2018-01-01 15:41
Just added some clarification about antiviruses
https://github.com/javascript-obfuscator/javascript-obfuscator#antiviruses-false-positive-virus-alerts

**Comment by sanex3339** [comment] 2018-01-01 15:44
Also you can attach all files with false positive here:
https://www.avast.ru/false-positive-file-form.php

**Comment by sanex3339** [comment] 2018-01-01 15:57
Also i wrote letter to `Avast` about false positive alerts. Will waiting for response.

**Comment by datio** [comment] 2018-01-09 17:46
I had the same issue back in 2011 with an obfuscated-with-Jscrambler MooTools library I had written.

I've long lost the source code of that lib (was using the obfuscated version in a CodeCanyon demo), but I vividly remember an issue where my hosting provider got quite concerned because of a virus report they received due to that obfuscated javascript file.

Googling the name of the library returned a forum post [1] that has the MD5 hash for that file listed, along with the false-positive virus name: ```unknown_html_RFI_eval```

Looking it up with VirusTotal results that it's clean [2].

[1] https://www.malwaredomainlist.com/forums/index.php?topic=3190.2280
[2] https://www.virustotal.com/#/file/ed59d45cab198d6f751f2207f1f07182d2c129fd015249c1e5203b155c3f1371/detection

**Comment by simpleplana** [comment] 2018-02-05 09:09
hi, please look, i try install this version 0.14.0 today but is not possible in npm.

**Comment by sanex3339** [comment] 2018-02-05 09:55
Hi, please make separate issue and describe all your steps and errors (if they was)

**Comment by tech1e** [comment] 2018-03-05 06:12
I can't install it now:
```
$ npm install javascript-obfuscator

> javascript-obfuscator@0.14.3
...
```

Avast 13.4 with virus definitions(18030400) steps in and puts in quarantive:

```
File: node_modules/.staging/javascript-obfuscator-f8cb28e3/dist/index.js
Infection: JS:Agent-EEEL [Trj]
```

**Comment by tech1e** [comment] 2018-03-05 06:44
Uploading the `index.js` file to virus total shows the same issue with Avast & AVG:

https://www.virustotal.com/#/file-analysis/YzdjMmI1ZTZjYmMyZTlhOWQzNTM3YmI3MGVlOGFmNDk6MTUyMDIzMjE1MA==

**Comment by sanex3339** [comment] 2018-03-05 07:15
Interesting. Avast and AVG is triggering on this lines:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/templates/string-array-nodes/string-array-rotate-function-node/StringArrayRotateFunctionTemplate.ts#L6-L14

When i removed it, all checks are passed.
So, i'll think how to fix this.

**Comment by sanex3339** [comment] 2018-03-05 15:54
@tech1e 
```
Hello, 

Thank you for reporting this false positive.

Our virus specialists have now cleared its reputation in our database.

With URLs this change should be instant, but it might take up to 24 hours with files.

For future reference you might also find the following article to be useful: Avast Clean Guidelines.
```

So, we should wait until tomorrow.

**Comment by sanex3339** [comment] 2018-03-06 20:43
Please, check again. Looks like `avast` fixed false-positive alert.

**Comment by sanex3339** [comment] 2018-06-06 09:33
Looks like no more problems with it. Reopen issue if you will have problems with avast.

**Closed by sanex3339** 2018-06-06 09:33 UTC
Labels: help wanted, high priority, need more info

**Comment by sanex3339** [comment] 2018-07-18 06:31
Anyone runs into thisbissue this week?

**Comment by davidroze** [comment] 2018-07-19 12:54
@sanex3339  Yes for some reason Avast and Bitdefender detects the obfuscated code as malicious again.

**Comment by sanex3339** [comment] 2018-07-19 13:02
Can you test with 0.16.0 version please?

**Comment by dani3lL** [comment] 2018-07-27 17:47
Hi, for some reason the detection occurs when either mangled or hexadecimal options selected and a prefix is used , if you will use only hexadecimal no detection will occur.

**Comment by voxsoftware** [comment] 2019-05-09 08:52
Is this false positive ocurred if output file looks like this:
1. convert to base64 
2. use something like ```var code= atob("xxxxx"); eval(code)```

**Comment by cliqer** [comment] 2021-09-05 18:18
This is still a problem in ES3 where var is being used.
If replaced by const/let it is not flagged as a false positive but then it doesn't work in ie. windows JScript engine that requires ES3.

**Comment by JanMakur** [comment] 2023-04-09 08:50
@cliqer is right , i've made a program based on mshta and i'm fasing the same problem
