### ISSUE TITLE
ReferenceError: _0xXXXX is not defined

### ISSUE THREAD

**Issue by 1-Imperialdramon-1** [javascript-obfuscator/javascript-obfuscator#207] opened 2018-02-27 08:30 UTC
Hi, 

I'm using javascript-obfuscator 0.14.3 (inside of webpack-obfuscator, also with the same version), and I'm getting this error:

![imagen](https://user-images.githubusercontent.com/36854734/36717849-f7777c1a-1b9f-11e8-9ffd-71d0936b6916.png)

ReferenceError: _0xXXXX is not defined, where "XXXX" changes for each execution.

I tried using:
```
deadCodeInjection: false
mangle: false
```

and the problem still occurs.

My configuration now is:

    selfDefending: false,
    stringArrayEncoding: true,
    stringArrayThreshold: 1,
    deadCodeInjection: false,
    mangle: false

This is the part of obfuscated source code that throws error:

`(function _0x3b6d2d(_0x593bc4){function _0x527df2(_0x4fad58){if(_0x943f83[_0x4fad58])return _0x943f83[_0x4fad58][_0x51e3('0x0')];var _0x290f37=_0x943f83[_0x4fad58]={'i':_0x4fad58,'l':!0x1,'exports':{}};return _0x593bc4[_0x4fad58][_0x51e3('0x1')](_0x290f37[_0x51e3('0x0')],_0x290f37,_0x290f37[_0x51e3('0x0')],_0x527df2),_0x290f37['l']=!0x0,_0x290f37[_0x51e3('0x0')];}var _0x943f83={};_0x527df2['m']=_0x593bc4,_0x527df2['c']=_0x943f83,_0x527df2['i']=function(_0x5e867c){return _0x5e867c;},_0x527df2['d']=function(_0x44d323,_0x48348f,_0x4f60fd){_0x527df2['o'](_0x44d323,_0x48348f)||Object[_0x51e3('0x2')](_0x44d323,_0x48348f,{'configurable':!0x1,'enumerable':!0x0,'get':_0x4f60fd});},_0x527df2['n']=function(_0xef5a1d){var _0x943f83=_0xef5a1d&&_0xef5a1d[_0x51e3('0x3')]?function(){return _0xef5a1d[_0x51e3('0x4')];}:function(){return _0xef5a1d;};return _0x527df2['d'](_0x943f83,'a',_0x943f83),_0x943f83;},_0x527df2['o']=function(_0x43b982,_0x1a5087){return Object[_0x51e3('0x5')][_0x51e3('0x6')][_0x51e3('0x1')](_0x43b982,_0x1a5087);},_0x527df2['p']='/',_0x527df2['oe']=function(_0x5bf88f){throw console[_0x51e3('0xd2')](_0x5bf88f),_0x5bf88f;};var _0x1fba40=_0x527df2(_0x527df2['s']=10);return _0x1fba40[_0x51e3('0x4')]||_0x1fba40;})({10: function (_0x26b38e,_0x462b99,_0x2e596b){'use strict';Object[_0x51e3('0x2')](_0x462b99,_0x51e3('0x3'),{'value':!0x0});var _0x4a2765=_0x2e596b(0x7),_0x35214f=_0x2e596b(0x1),_0x424a11=_0x2e596b(0x0),_0x5e8075=_0x2e596b(0x5),_0x4c2cc3=_0x2e596b['n'](_0x5e8075),_0x8bb5aa=function(_0x18d860){var _0x462b99=new _0x4c2cc3['a']();_0x462b99[_0x51e3('0xecf')]=function(_0x4257d4){for(var _0x2e596b=arguments[_0x51e3('0xa')],_0x4b3ad4=Array(_0x2e596b>0x1?_0x2e596b-0x1:0x0),_0x2237a8=0x1;_0x2237a8<_0x2e596b;_0x2237a8++)_0x4b3ad4[_0x2237a8-0x1]=arguments[_0x2237a8];_0x462b99[_0x51e3('0x1d')][_0x51e3('0x11')](_0x462b99,[_0x4257d4,_0x4257d4][_0x51e3('0xb')](_0x4b3ad4));},_0x462b99[_0x51e3('0x1a')]=function(_0x2a5dfc){for(var _0x2e596b=arguments[_0x51e3('0xa')],_0x3279d9=Array(_0x2e596b>0x1?_0x2e596b-0x1:0x0),_0x4dcfda=0x1;_0x4dcfda<_0x2e596b;_0x4dcfda++)_0x3279d9[_0x4dcfda-0x1]=arguments[_0x4dcfda];_0x462b99[_0x51e3('0x1b')][_0x51e3('0x11')](_0x462b99,[_0x2a5dfc][_0x51e3('0xb')](_0x3279d9));};var _0x2e596b=function(_0x47afc3,_0x7069a3){_0x18d860[_0x51e3('0xb23')]({'event':_0x47afc3,'data':_0x7069a3});};_0x18d860[_0x51e3('0x97d')](_0x51e3('0x1149'),function(_0x1c7ed0){_0x18d860[_0x51e3('0xfd2')]=_0x1c7ed0;}),_0x18d860[_0x51e3('0x97d')](_0x51e3('0xeb'),function(_0x109a81){var _0x4c7c9b=_0x109a81[_0x51e3('0xb8a')];switch(_0x4c7c9b[_0x51e3('0x13ff')]){case _0x51e3('0x1149'):_0x18d860[_0x51e3('0xfd2')]=_0x4c7c9b[_0x51e3('0xfd2')];break;case _0x51e3('0x33'):var _0x5ee0e9=JSON[_0x51e3('0x49')](_0x4c7c9b[_0x51e3('0xec2')]);_0x18d860[_0x51e3('0x100c')]=new _0x4a2765['a'](_0x462b99,_0x4c7c9b[_0x51e3('0xf60')],_0x5ee0e9,_0x4c7c9b[_0x51e3('0x970')],_0x18d860[_0x51e3('0xfd2')]);try{Object(_0x424a11['a'])(!0x0===_0x5ee0e9[_0x51e3('0xa87')]);}catch(_0x464bfa){console[_0x51e3('0xa8b')](_0x51e3('0x154e'));}_0x2e596b(_0x51e3('0x33'),null);break;case _0x51e3('0x1011'):_0x18d860[_0x51e3('0x100c')][_0x51e3('0xe')](_0x4c7c9b[_0x51e3('0xb8a')],_0x4c7c9b[_0x51e3('0xf53')],_0x4c7c9b[_0x51e3('0xfcd')],_0x4c7c9b[_0x51e3('0xf20')],_0x4c7c9b[_0x51e3('0xf21')],_0x4c7c9b[_0x51e3('0x154f')],_0x4c7c9b[_0x51e3('0x1550')],_0x4c7c9b[_0x51e3('0x1551')],_0x4c7c9b[_0x51e3('0xf72')],_0x4c7c9b[_0x51e3('0x976')],_0x4c7c9b[_0x51e3('0x1552')],_0x4c7c9b[_0x51e3('0x1553')]);}}),_0x462b99['on'](_0x35214f['a'][_0x51e3('0x100f')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0xf1f')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0xfde')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0xa8')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0x100a')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0x100b')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0xf39')],_0x2e596b),_0x462b99['on'](_0x35214f['a'][_0x51e3('0xff7')],function(_0x1f293f,_0x5568c3){var _0x5000d2=[],_0x17b1ae={'event':_0x1f293f,'data':_0x5568c3};_0x5568c3[_0x51e3('0x114f')]&&(_0x17b1ae[_0x51e3('0x114f')]=_0x5568c3[_0x51e3('0x114f')][_0x51e3('0xec0')],_0x5000d2[_0x51e3('0xe')](_0x5568c3[_0x51e3('0x114f')][_0x51e3('0xec0')]),delete _0x5568c3[_0x51e3('0x114f')]),_0x5568c3[_0x51e3('0x1150')]&&(_0x17b1ae[_0x51e3('0x1150')]=_0x5568c3[_0x51e3('0x1150')][_0x51e3('0xec0')],_0x5000d2[_0x51e3('0xe')](_0x5568c3[_0x51e3('0x1150')][_0x51e3('0xec0')]),delete _0x5568c3[_0x51e3('0x1150')]),_0x18d860[_0x51e3('0xb23')](_0x17b1ae,_0x5000d2);});};_0x462b99[_0x51e3('0x4')]=_0x8bb5aa;}})(self);`

Do you know why this happens? How could we debug this?
Thanks in advance for your help.

**Comment by sanex3339** [comment] 2018-02-27 09:07
Can you disable webpack obfuscator, bundle your project without it and then obfuscate your bundle with `javascript-obfuscator` CLI?

This error still will happen?

**Comment by sanex3339** [comment] 2018-02-27 09:13
_0x51e3 is a name of string array calls wrapper. It should be appended to the source code beyond the string array with collected string literals. So in your case for some reason this name is not defined that is strange, but looks like some conflict between vsriable names.

**Comment by 1-Imperialdramon-1** [comment] 2018-02-27 09:40
Hi @sanex3339, 

I have just check this, and the issue persist.
I have tried into CLI: `javascript-obfuscator ./dist/input.js --output output_file_name.js`, and the issue remains.

I have only one bundle (one output in module.exports).
Please let me know your thoughts about this.

**Comment by sanex3339** [comment] 2018-02-27 09:53
Interesting. Can you send me your full obfuscated file via email?

**Comment by 1-Imperialdramon-1** [comment] 2018-02-27 10:30
Sure. How can i know your email address?

**Comment by sanex3339** [comment] 2018-02-27 10:46
javascript-obfuscator@yandex.ru

**Comment by 1-Imperialdramon-1** [comment] 2018-02-28 10:35
Hi @sanex3339, I sent you an email with the files attached. 
Please, let me know if you need anything else.

Thanks in advance.

**Comment by sanex3339** [comment] 2018-02-28 10:37
Thanks. I'll check it this weekend

**Comment by sanex3339** [comment] 2018-02-28 21:34
You sent me email without attachments

**Comment by sanex3339** [comment] 2018-03-01 07:53
No. A didn't receive any attachments

**Comment by 1-Imperialdramon-1** [comment] 2018-03-01 08:11
Ok, I will send you the files using wetransfer. Really sorry for the
inconvenience.
If you have troubles, don't hesitate to ask me.

**Comment by sanex3339** [comment] 2018-03-01 22:23
What browser did you use?

**Comment by 1-Imperialdramon-1** [comment] 2018-03-02 07:12
It doesn't mind. But now I'm using Google Chrome to apply testing.

**Comment by sanex3339** [comment] 2018-03-02 07:22
I tested on chrome and it worked fine for me, without any error.

**Comment by 1-Imperialdramon-1** [comment] 2018-03-02 08:23
Hi @sanex3339 ,

How did you test this? Should I send you instructions to test this privately? 
Please note that some of this code might run on a web worker using MSE (https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API). Could this be the cause of the issue?

Thanks,

**Comment by sanex3339** [comment] 2018-03-02 08:33
I just include this script on html page.
I saw react message, no errors.

**Comment by 1-Imperialdramon-1** [comment] 2018-03-02 11:13
Hi @sanex3339 ,

Thanks for the information. I have tried disabling the web workers and the log is no longer shown. However I would like to keep using it for performance reasons.

I have tried disabling `stringArrayEncoding: false,`, but the issue still happens.
You mentioned obfuscating it separately, would I need to do this manually? Do you have any advice for that? Is there some setting that could make this work without changing the structure of the project? Please let me know your thoughts on this.

Thanks,

**Comment by sanex3339** [comment] 2018-03-02 11:15
Extract code that will used by web workers into separate bundle or chunk by webpack.

**Comment by sanex3339** [comment] 2018-03-02 18:51
Without changing the structure of your project you can disable `stringArrray` option, but this is core option and many other options depending on it.

Best option for you is to wrap web worker code inside conditional comments, after that this code won't be obfuscated at all. Check readme for more details.

**Comment by carverdo** [comment] 2018-03-10 16:38
Hi guys, I fell to this page as I've just come across a very similar issue. 

I can generate the error in chrome after online obfuscating this simple instruction: 
$(document).ready(function() { console.log("bosh"); });

Was there any resolution to the problem?

**Comment by sanex3339** [comment] 2018-03-10 18:02
Hi, can you send options with which i can reproduce this error

**Comment by sanex3339** [comment] 2018-03-10 20:33
@1-Imperialdramon-1 hi, any news?

**Comment by sanex3339** [comment] 2018-03-10 21:18
@carverdo cannot reproduce, what options did you use?

**Comment by carverdo** [comment] 2018-03-10 21:19
Just coming guys...

**Comment by carverdo** [comment] 2018-03-10 21:27
Sorry Timofey, I got distracted (late on a Saturday night).

So, I was originally going to write this email -
I go to this url: https://javascriptobfuscator.herokuapp.com/

I enter the simple js: 
`$(document).ready(function() {    console.log("bosh"); });`
And hit obfuscate without changing any of the settings to generate the error.

But now I can't - it works perfectly. More importantly so do the 8 other files I'm trying to obfuscate.

I don't really know why this might be. To try and be of some help, here's the couple of things I'm physically doing differently -
1. I am now at home (not the office);
1.b Same machine / browser (chrome);
2. Instead of assuming the obfuscated code is fully selected in your url, I go in, deselect, and then select all before copying.
3. I did tinker with some of the seed settings earlier (prior to refreshing tonight) and noticed that it seemed to have some odd behaviour (resetting the script to be obfuscated);
4. I am taking more time now (was getting frustrated before I took a break) so there is a chance of human error, but 
5. The error was very consistent. I haven't got a good snippet any more but it was always the reference to "data". Here's half a snippet from earlier:
.... [many lines of code]
`if(!_0x1ed231){data;}else{return;}_0x38f2e8();});_0xb9afbd();var GEOPOS_URL=_0x3bd9('0xa')`
... [my code; e.g. the first var I reference in that particular js file is the term you see above GEOPOS_URL]

The error always came about from that "data" definition near the start as part of the `if` statement.

**Comment by sanex3339** [comment] 2018-03-10 21:31
aah, looks like you used `selfDefending` option. If you using this option, you shouldn't change your obfuscated code. 

```
if(!_0x1ed231){data;}
```
This error `data is not defined` is self defending mechanism that will break your code if code was changed. So, maybe you format your code after obfuscation with `selfDefending` option?

**Comment by carverdo** [comment] 2018-03-10 21:40
I could well believe that - the obfuscated code feels shorter / different in character tonight - so I could easily see that I had inadvertently checked that box earlier.

What type of formatting might you mean? I select from your url and copy into a js file (and it drops in as one line).

**Comment by sanex3339** [comment] 2018-03-10 21:42
Any reformat that will beautify your code or change unicode escape sequence strings to a normal format.

**Comment by carverdo** [comment] 2018-03-10 21:45
Hhmm. I'll tinker with that the morrow and trouble you no more tonight. 

I didn't say it earlier, but it's worth saying: thanks very much for the very cool bit of kit you fellows have built, and for all the help tonight. You've helped solved a mystery.

**Comment by sanex3339** [comment] 2018-03-21 21:25
Ping

**Comment by carverdo** [comment] 2018-03-22 17:41
Sorry, was that fat fingers or are you expecting something from me (apologies if I've kept you waiting)?

**Comment by sanex3339** [comment] 2018-03-22 17:45
Did you check it? Can i close this issue?

**Comment by carverdo** [comment] 2018-03-22 18:13
Sorry, absolutely close this issue - you were spot on. My apologies.

PS Coincidently I might be about to open another one on jquery...

**Closed** 2018-03-22 18:14 UTC
Labels: need more info
