### ISSUE TITLE
[Feature Request] Better Self Defender

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#755] opened 2020-09-19 20:11 UTC
Okey, in #754 I has been misstake with title. 
What about create smarter defender not like the current?

For example: **Create a hash of current code. If hash is different - broke code.**
Second way: **Check length of current code.**
Third way: **Create few hashes of few functions and check this hashes.** (this way for too long code)

For example:

```
const kruzya = 0;

function getKruzya() { return kruzya +1}; // we get hash of this function (just for example)

console.log(getKruzya());
```

in obfuscate mode:
```
const hashes = [{function: _0x2, hash: "ABC"}]; // just example hash
const 0x1 = 0; 
function _0x2() {return 0x1 + 1};       // so if I edit this function, name, or body (content/context) of function - code just broke.
console.log( _0x2());
// just typo example
function check() {
const e = hashes[0];

if (typeof e.function !== "undefined") // check if func is exist ...
    const body = e.functionName;
   if (!body || !body.length) BROKE_CODE(); // note: just second check but I think this is optional.
  const newHash = getHash(body);
  const oldHash = e.hash;

  if (oldHash !== newHash) BROKE_CODE();
}
else BROKE_CODE(); // just typo example
```

~~and yep. This is all. I didn't think about **HOW TO CHECK HASH.** But I **hope** this is simple :eyes:~~
**My code is just example.**

**Comment by BlackYuzia** [comment] 2020-09-19 20:13
> For example: Create a hash of current code. If hash is different - broke code.
Seconds way: Check length of current code.
Third way: Create few hashes of few functions and check this hashes. (this way for too long code)

four way: **We can do all or semi-all of this things.**

**Comment by sanex3339** [comment] 2020-09-20 17:49
Seems it's a duplicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/755

**Closed** 2020-09-20 17:50 UTC

**Comment by BlackYuzia** [comment] 2020-09-20 17:54
@sanex3339 lol. #755 (this) duplicate of #755? **WAT** :eyes:

**Comment by sanex3339** [comment] 2020-09-20 17:55
Oh. Fixed the link.

**Comment by sanex3339** [comment] 2020-09-20 17:57
> @sanex3339 lol. #755 (this) duplicate of #755? **WAT** 👀
> 
> > Anyway, not in the nearest plans
> 
> Ok :c

The main problem is that such kind of code can be easily detected and removed. So right now I'm more focused on code transformations than on additional code helpers.
