### ISSUE TITLE
NodeJS: SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by LucasBrazi06** [javascript-obfuscator/javascript-obfuscator#50] opened 2017-04-28 23:44 UTC
Hi,

I obfuscated my whole NodeJS project with you Grunt task and when I want to run it I got this syntax error.

> SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Data\Private\Innovation\EV\ev-server\dist\client\soap\SoapChargingStationClient.js:1:6037)
    at Module._compile (module.js:570:32)

I tried several other options (medium obfuscation, optimal performance...) without success.

I search a solution but found nothing. 

Any clue?

Thanks,
Serge.

**Comment by sanex3339** [comment] 2017-04-29 11:03
Hi, can you provide more detailed error message? Also i will very happy if you send me small project with example of current problem, it help me to reproduce the error.

**Comment by LucasBrazi06** [comment] 2017-05-01 10:54
Hi,

Find attached the part that fails.

Just rename the 'pdf' to 'zip' :-) and unpack it, do 'npm install' + 'grunt' to get the syntax error.

Thanks!
Serge.


[src.pdf](https://github.com/javascript-obfuscator/javascript-obfuscator/files/967706/src.pdf)

**Comment by sanex3339** [comment] 2017-05-02 18:00
Tnx, i'll look at this right now

**Comment by sanex3339** [comment] 2017-05-02 18:27
How i can build dist files? grunt task `grunt.registerTask("build:prod", ["clean", "uglify"]);` without `["clean", "uglify"]` doesn't generate `dist` folder

**Comment by sanex3339** [comment] 2017-05-02 18:46
It's a bug!

**Comment by sanex3339** [comment] 2017-05-02 18:46
I'll fix it soon as possible (today)

**Comment by sanex3339** [comment] 2017-05-02 19:39
`javascript-obfuscator@0.9.3` out! Please reinstall `grunt-contrib-obfuscator`, new version of `javascript-obfuscator` should automatically install after that.

**Comment by slig** [comment] 2017-05-02 19:46
Since the `grunt-contrib-obfuscator`'s package.json specified ` "javascript-obfuscator": "^0.8.1"`, it won't pull the new version of `javascript-obfuscator` because it's `0.9.x` and not `0.8.x`, I believe.

**Comment by sanex3339** [comment] 2017-05-02 19:53
Can you update it?

**Comment by slig** [comment] 2017-05-02 19:59
Updated to a new version `grunt-contrib-obfuscator@3.0.0`.

**Comment by sanex3339** [comment] 2017-05-02 20:00
Thank you!

**Comment by slig** [comment] 2017-05-02 20:01
You're welcome. I should've followed the same version number you use on your package. Would've been much easier to understand.

**Comment by qingweiqm** [comment] 2017-05-03 01:37
Hi,all

 

I just download the 0.9.3 file, and npm install grunt-contrib-obfuscator, then try to install the new version with “npm install --save-dev javascript-obfuscator”, but got the following errors:

 

 

and the attached file is the npm-debug log, can anyone help to check it.

 

Many thanks!

 

 

 

发件人: <bounces+848413-93a5-qingweily=126.com@sgmail.github.com> 代表 Tiago Serafim <notifications@github.com>
答复: javascript-obfuscator/javascript-obfuscator <reply@reply.github.com>
日期: 2017年5月3日 星期三 上午3:59
至: javascript-obfuscator/javascript-obfuscator <javascript-obfuscator@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [javascript-obfuscator/javascript-obfuscator] NodeJS: SyntaxError: Unexpected identifier (#50)

 

Updated to a new version grunt-contrib-obfuscator@3.0.0.

**Comment by qingweiqm** [comment] 2017-05-03 02:34
hi, all 

Just rename the name part of the package.json file with new name and it’s done.



Many thanks!

**Comment by qingweiqm** [comment] 2017-05-03 03:21
it seems there is no server.js after the installation, how can I start the local server ?




Many thanks!

**Comment by sanex3339** [comment] 2017-05-03 05:58
Hmm, @qingweiqm, i slightly don't understand context of last three messages, can you describe it?

**Comment by qingweiqm** [comment] 2017-05-03 06:06
The third message is meaningless.  Pls ignore. My fault.

 

The first  message is when using npm install the new version, there is an error, just fixed with the second message mentioned.

 

And do I just modify the package.json on javascript-obfuscator-ui to get the 0.10.0-beta2 version ?

 

Regards!

 

发件人: <bounces+848413-93a5-qingweily=126.com@sgmail.github.com> 代表 Timofey Kachalov <notifications@github.com>
答复: javascript-obfuscator/javascript-obfuscator <reply@reply.github.com>
日期: 2017年5月3日 星期三 下午1:58
至: javascript-obfuscator/javascript-obfuscator <javascript-obfuscator@noreply.github.com>
抄送: qingweiqm <qingweily@126.com>, Mention <mention@noreply.github.com>
主题: Re: [javascript-obfuscator/javascript-obfuscator] NodeJS: SyntaxError: Unexpected identifier (#50)

 

Hmm, @qingweiqm, i slightly don't understand context of last three messages, can you describe it?

**Comment by sanex3339** [comment] 2017-05-03 06:08
I don't see any attached files, can you paste it here manually?

**Comment by qingweiqm** [comment] 2017-05-03 06:11
pls see below:


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'javascript-obfuscator' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData javascript-obfuscator
8 silly fetchNamedPackageData javascript-obfuscator
9 silly mapToRegistry name javascript-obfuscator
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'javascript-obfuscator',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'javascript-obfuscator',
12 silly mapToRegistry   name: 'javascript-obfuscator',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/javascript-obfuscator
14 verbose request uri https://registry.npmjs.org/javascript-obfuscator
15 verbose request no auth needed
16 info attempt registry request try #1 at 09:28:58
17 verbose request id 0af208d7bec7f3af
18 verbose etag W/"5908df5b-29484"
19 verbose lastModified Tue, 02 May 2017 19:34:51 GMT
20 http request GET https://registry.npmjs.org/javascript-obfuscator
21 http 304 https://registry.npmjs.org/javascript-obfuscator
22 verbose headers { date: 'Wed, 03 May 2017 01:29:00 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5908df5b-29484"',
22 verbose headers   age: '149',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-hkg6823-HKG',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1493774940.087939,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Wed, 03 May 2017 01:29:00 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5908df5b-29484"',
23 silly get     age: '149',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hkg6823-HKG',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1493774940.087939,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/javascript-obfuscator from cache
25 verbose get saving javascript-obfuscator to /Users/liuyong/.npm/registry.npmjs.org/javascript-obfuscator/.cache.json
26 verbose correctMkdir /Users/liuyong/.npm correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install javascript-obfuscator as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/liuyong/Documents/personal/personal enterprise/product&Road map/shadow_transformer-0.9.3
45 error Darwin 15.6.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "javascript-obfuscator"
47 error node v6.9.4
48 error npm  v3.10.10
49 error code ENOSELF
50 error Refusing to install javascript-obfuscator as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
 

regards!

**Comment by sanex3339** [comment] 2017-05-03 06:15
strange, because i installed 0.9.3 version without any problems
![image](https://cloud.githubusercontent.com/assets/9210534/25649766/fb4c7896-2fe0-11e7-97e9-656443419bdf.png)

**Comment by sanex3339** [comment] 2017-05-03 06:20
if you want to use new version of `javascript-obfuscator` with `grunt-contrib-obfuscator`, you should just update `grunt-contrib-obfuscator` to `3.0.0` version, `javascript-obfuscator` will install automatically

**Comment by qingweiqm** [comment] 2017-05-03 06:24
Got it. Thanks!

 

 

发件人: <bounces+848413-93a5-qingweily=126.com@sgmail.github.com> 代表 Timofey Kachalov <notifications@github.com>
答复: javascript-obfuscator/javascript-obfuscator <reply@reply.github.com>
日期: 2017年5月3日 星期三 下午2:20
至: javascript-obfuscator/javascript-obfuscator <javascript-obfuscator@noreply.github.com>
抄送: qingweiqm <qingweily@126.com>, Mention <mention@noreply.github.com>
主题: Re: [javascript-obfuscator/javascript-obfuscator] NodeJS: SyntaxError: Unexpected identifier (#50)

 

if you want to use new version of javascript-obfuscator with grunt-contrib-obfuscator, you should just update grunt-contrib-obfuscator to 3.0.0 version, javascript-obfuscator will install automatically

**Comment by LucasBrazi06** [comment] 2017-05-03 21:15
Hi,
I upgraded to the last version and still get the same error when running 'grunt build:prod'.
    "grunt-contrib-obfuscator": "^3.0.0",
    "javascript-obfuscator": "^0.9.3"

Cheers,
Serge.

**Comment by sanex3339** [comment] 2017-05-03 21:19
you don't need `"javascript-obfuscator": "^0.9.3"` line, just reinstall `grunt-contrib-obfuscator`:
`npm uninstall grunt-contrib-obfuscator --save-dev`
and install it again
`npm i grunt-contrib-obfuscator --save-dev`

Or you can type `npm update` and this command should update all your dependencies.

After that check your `node_modules/escodegen-wallaby` folder. This folder should exist.

**Comment by sanex3339** [comment] 2017-05-04 08:07
`javascript-obfuscator@0.9.4` out. Added runtime performance boost with `stringArrayEncoding: 'rc4'`

**Comment by LucasBrazi06** [comment] 2017-05-07 14:55
I did as you advised and checked the version, updated but still same compil issue since the beginning: SyntaxError: Unexpected token: name (ChargingStationClient)

**Comment by sanex3339** [comment] 2017-05-07 21:15
hmm

**Comment by LucasBrazi06** [comment] 2017-05-07 23:32
And ? :-)

**Comment by sanex3339** [comment] 2017-05-08 07:46
I will look, but not now and not today =( Sorry, but today i haven't time for programming =(

**Comment by LucasBrazi06** [comment] 2017-05-08 08:39
No problem :-)

**Comment by sanex3339** [comment] 2017-05-11 18:37
I obfuscated both `ChargingStationClient.js` and  `SoapChargingStationClient.js` without any problems.

**Comment by sanex3339** [comment] 2017-05-11 18:39
Can you provide another example? In previous example grunt task didn't work at first, i edited `gruntfile` to run it.

**Comment by sanex3339** [comment] 2017-05-17 20:53
ping

**Comment by LucasBrazi06** [comment] 2017-05-18 22:24
pong :)

Sorry I'm on holiday and I'm going back soon.

I'll provide you another example.

Cheers!

**Comment by sanex3339** [comment] 2017-05-19 06:06
Ok

**Comment by sanex3339** [comment] 2017-05-31 12:13
ping :)

**Comment by sanex3339** [comment] 2017-06-20 10:13
ping

**Comment by sanex3339** [comment] 2017-06-28 22:28
Closed due to inactivity

**Closed** 2017-06-28 22:28 UTC
