### ISSUE TITLE
Graphql tags do not get obfuscated?

### ISSUE THREAD

**Issue by NullScope** [javascript-obfuscator/javascript-obfuscator#696] opened 2020-08-05 19:45 UTC
I am using apollo client on my electron app and I have noticed that [graphql tags](https://www.npmjs.com/package/graphql-tag) do not get obfuscated, is this normal behaviour? Here is an example of the obfuscated result:

![image](https://user-images.githubusercontent.com/4614486/89456864-6f26d380-d75c-11ea-8c56-098380ce5751.png)

And here is the config that I use:

```
test: /\.(tsx?|jsx?)$/i,
    exclude: /(node_modules|\.webpack)/,
    include: path.resolve(__dirname, 'src'),
    enforce: 'post',
    use: [
      {
        loader: WebpackObfuscator.loader,
        options: {
          compact: true,
          controlFlowFlattening: false,
          controlFlowFlatteningThreshold: 0.75,
          deadCodeInjection: true,
          deadCodeInjectionThreshold: 1,
          debugProtection: true,
          debugProtectionInterval: true,
          disableConsoleOutput: true,
          domainLock: [],
          identifierNamesGenerator: 'hexadecimal',
          identifiersDictionary: [],
          identifiersPrefix: '',
          inputFileName: '',
          log: false,
          numbersToExpressions: true,
          renameGlobals: false,
          renameProperties: false,
          reservedNames: [],
          reservedStrings: [],
          rotateStringArray: true,
          seed: new Date().getTime(),
          selfDefending: false,
          shuffleStringArray: true,
          simplify: true,
          sourceMap: false,
          sourceMapBaseUrl: '',
          sourceMapFileName: '',
          sourceMapMode: 'separate',
          splitStrings: true,
          splitStringsChunkLength: 10,
          stringArray: true,
          stringArrayEncoding: 'rc4',
          stringArrayThreshold: 1,
          target: 'node',
          transformObjectKeys: true,
          unicodeEscapeSequence: true,
        },
      },
    ],
```

**Comment by sanex3339** [comment] 2020-08-05 19:52
Will check it

**Comment by sanex3339** [comment] 2020-08-05 19:54
I disabled obfuscation of tagged template literals, but i don't remember - why.
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/node-transformers/converting-transformers/TemplateLiteralTransformer.ts#L48

**Comment by NullScope** [comment] 2020-08-05 20:05
Ah alright thank you, does that mean it will never be a feature or it will not be planned as a feature for now?

**Comment by sanex3339** [comment] 2020-08-05 20:22
Hmm, actually i know away to do this

**Comment by NullScope** [comment] 2020-08-05 21:28
Good to hear, hopefully it will go well! I can test it when it becomes available

**Comment by sanex3339** [comment] 2020-08-06 20:27
Merged to the `master` branch.

**Comment by sanex3339** [comment] 2020-08-06 20:34
I'll release new version in few days, you can try to test it right now directly from `github`

**Comment by sanex3339** [comment] 2020-08-08 07:05
Hi. As soon as you check it, I release a new release with it.

**Comment by NullScope** [comment] 2020-08-10 16:51
Hi, sorry for the late reply I will try it right now

**Comment by NullScope** [comment] 2020-08-10 17:32
I tried downloading this repo and `webpack-obfuscator` repo and installed `webpack-obfuscator` as a local module of my project and this repo as a local module of `webpack-obfuscator`, and then did `npm install` on both, I am not sure if that is the right approach to testing this as I am getting a few errors as shown down below, is there something else I have to do?

```
An unhandled error has occurred inside Forge:
Compilation errors in the main process: Hash: cbf721a3db081291397d
Version: webpack 4.44.1
Time: 45326ms
Built at: 08/10/2020 18:23:38
                                      Asset      Size  Chunks             Chunk Names
assets/ee6eaa615c3cd93a1c4cf749039fa8fe.ico  14.7 KiB          [emitted]  
                                   index.js   992 KiB       0  [emitted]  main
Entrypoint main = index.js
 [19] external "path" 42 bytes {0} [built]
 [29] ./node_modules/@apollo/client/core/index.js 1010 bytes {0} [built]
 [46] external "electron" 42 bytes {0} [built]
 [47] ./node_modules/@apollo/client/index.js 100 bytes {0} [built]
 [49] ./node_modules/electron-store/index.js 766 bytes {0} [built]
 [79] ./node_modules/@apollo/client/react/index.js 281 bytes {0} [built]
 [94] ./src/lib/API.ts 28.5 KiB {0} [built]
[107] ./src/index.ts 58.4 KiB {0} [built]
[205] ./src/assets/favicon/favicon.ico 61 bytes {0} [built]
[206] ./src/lib/Edge.ts 36.2 KiB {0} [built]
[208] ./src/lib/Cache.ts 31.5 KiB {0} [built]
[209] ./src/migrations/0.0.1.ts 25.3 KiB {0} [built]
[210] ./src/migrations/0.0.2.ts 30.1 KiB {0} [built]
[212] ./src/lib/Settings.ts 56.1 KiB {0} [built]
[277] ./node_modules/electron-squirrel-startup/index.js 1 KiB {0} [built]
    + 271 hidden modules

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/cli/utils/CLIUtils.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/cli/utils/CLIUtils.ts(32,26):
TS2304: Cannot find name '__non_webpack_require__'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/constants/EcmaVersion.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/constants/EcmaVersion.ts(3,14):
TS2322: Type '11' is not assignable to type '3 | 5 | 6 | 7 | 8 | 9 | 10 | 2015 | 2016 | 2017 | 2018 | 2019'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts(1,5):
TS2300: Duplicate identifier 'baz'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts(1,5):
TS2451: Cannot redeclare block-scoped variable 'baz'.

ERROR in C:/myapp/client/src/lib/webpack-obfuscator/loader/index.ts
ERROR in C:/myapp/client/src/lib/webpack-obfuscator/loader/index.ts(30,29):
TS2345: Argument of type 'Program' is not assignable to parameter of type 'Node'.
  Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Program' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Program'.
    Types of property 'body' are incompatible.
      Type '(Directive | ExpressionStatement | BlockStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | ExportAllDeclaration)[]' is not assignable to type '(BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive)[]'.
        Type 'Directive | ExpressionStatement | BlockStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | ExportAllDeclaration' is not assignable to type 'BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive'.
          Type 'Directive' is not assignable to type 'BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive'.
            Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Directive' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Directive'.
              Types of property 'expression' are incompatible.
                Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Literal' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Literal'.
                  Type 'SimpleLiteral' is not assignable to type 'Literal'.
                    Property 'regex' is missing in type 'SimpleLiteral' but required in type 'RegExpLiteral'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/cli/utils/CLIUtils.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/cli/utils/CLIUtils.ts(32,26):
TS2304: Cannot find name '__non_webpack_require__'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/constants/EcmaVersion.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/src/constants/EcmaVersion.ts(3,14):
TS2322: Type '11' is not assignable to type '3 | 5 | 6 | 7 | 8 | 9 | 10 | 2015 | 2016 | 2017 | 2018 | 2019'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts(1,5):
TS2300: Duplicate identifier 'baz'.

ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts
ERROR in C:/myapp/client/src/lib/javascript-obfuscator/test/fixtures/directory-obfuscation/baz.ts(1,5):
TS2451: Cannot redeclare block-scoped variable 'baz'.

ERROR in C:/myapp/client/src/lib/webpack-obfuscator/loader/index.ts
ERROR in C:/myapp/client/src/lib/webpack-obfuscator/loader/index.ts(30,29):
TS2345: Argument of type 'Program' is not assignable to parameter of type 'Node'.
  Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Program' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Program'.
    Types of property 'body' are incompatible.
      Type '(Directive | ExpressionStatement | BlockStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | ExportAllDeclaration)[]' is not assignable to type '(BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive)[]'.
        Type 'Directive | ExpressionStatement | BlockStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | ExportAllDeclaration' is not assignable to type 'BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive'.
          Type 'Directive' is not assignable to type 'BlockStatement | FunctionDeclaration | ExpressionStatement | EmptyStatement | DebuggerStatement | ... 20 more ... | Directive'.
            Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Directive' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Directive'.
              Types of property 'expression' are incompatible.
                Type 'import("C:/myapp/client/src/lib/webpack-obfuscator/node_modules/@types/estree/index").Literal' is not assignable to type 'import("C:/myapp/client/src/lib/javascript-obfuscator/node_modules/@types/estree/index").Literal'.
                  Type 'SimpleLiteral' is not assignable to type 'Literal'.
                    Property 'regex' is missing in type 'SimpleLiteral' but required in type 'RegExpLiteral'.
    at cb (C:\myapp\client\node_modules\@electron-forge\plugin-webpack\src\WebpackPlugin.ts:250:31)
    at finalCallback (C:\myapp\client\node_modules\webpack\lib\Compiler.js:257:39)
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\myapp\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at AsyncSeriesHook.lazyCompileHook (C:\myapp\client\node_modules\tapable\lib\Hook.js:154:20)
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (C:\myapp\client\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:298:10
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\myapp\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (C:\myapp\client\node_modules\tapable\lib\Hook.js:154:20)
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:482:27
    at C:\myapp\client\node_modules\neo-async\async.js:2818:7
    at done (C:\myapp\client\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\myapp\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at C:\myapp\client\node_modules\webpack\lib\Compiler.js:464:33
```

**Comment by sanex3339** [comment] 2020-08-11 06:56
No no no. If you're using `webpack-obfuscator` just try to install `javascript-obfuscator` from github:
```
npm i https://github.com/javascript-obfuscator/javascript-obfuscator.git
```

**Comment by NullScope** [comment] 2020-08-11 16:37
Ah, sorry about that, just did that and it works now, I tested and it seems to be obfuscating the literals and everything to be working just fine!

However `disableConsoleOutput` causes my app to hang, maybe its related to #691?

**Comment by sanex3339** [comment] 2020-08-11 16:51
What exactly happens when you turned on disableConsoleOutput option?

**Comment by NullScope** [comment] 2020-08-11 17:37
The app just hangs, I tested some more and 1.9.0 version also does this, I think the adition of xstate causes this issue, I will try to create a blanked app just with xstate to test

**Comment by NullScope** [comment] 2020-08-11 19:01
So the app freezing is very sporadic which I am still trying to understand why it happens, but xstate throws this error `e.console.log.bind is not a function` with the `disableConsoleOutput` option, I've looked at their source code and it's this block that causes the issues:

```
Interpreter.defaultOptions = /*#__PURE__*/function (global) {
    return {
      execute: true,
      deferEvents: true,
      clock: {
        setTimeout: function (fn, ms) {
          return global.setTimeout.call(null, fn, ms);
        },
        clearTimeout: function (id) {
          return global.clearTimeout.call(null, id);
        }
      },
      logger: global.console.log.bind(console),
      devTools: false
    };
  }(typeof window === 'undefined' ? global : window);
```
there is no way to avoid `logger: global.console.log.bind(console)` to run even if I try to override the default logger, is there a way to fix this problem or should I just disable `disableConsoleOutput`? Also should I create a different issue for this?

**Comment by sanex3339** [comment] 2020-08-11 19:16
Please createa different issue for this. I'll try to reproduce this.

**Comment by NullScope** [comment] 2020-08-11 19:41
I've created it here #702

**Comment by sanex3339** [comment] 2020-08-14 06:02
Released as `1.10.0`

**Closed by sanex3339** 2020-08-14 06:02 UTC
Labels: enhancement, waiting for release

**Comment by sanex3339** [comment] 2020-08-18 17:52
I will revert obfuscation of tagged template literals because of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/716#

**Comment by sanex3339** [comment] 2020-08-18 18:04
I'll release a new release with disabled `tagged template literals` obfuscation in a few hours.

I don't sure if i want to transpile `tagged template literals` like `babel` does:

*input*
```
const tag = (strings, ...args) => {
  return strings.raw
};

tag`begin${'first'}middle${'second'}end`;
```

*output*
```
"use strict";

function _templateObject() {
  var data = _taggedTemplateLiteral(["begin", "middle", "end"]);

  _templateObject = function _templateObject() {
    return data;
  };

  return data;
}

function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

var tag = function tag(strings) {
  return strings.raw;
};

tag(_templateObject(), 'first', 'second');
```

**Comment by sanex3339** [comment] 2020-08-18 18:43
Released `1.11.0` with disabled `tagged template literals` obfuscation.

**Comment by NullScope** [comment] 2020-08-18 22:34
Ah, that's a shame it caused bugs, it does work with graphql however, maybe a solution would be to have an option what kind of tagged template literals it should obfuscate? Or is that considered too much "duct tape" for this problem?

**Comment by sanex3339** [comment] 2020-08-21 08:44
Created PR with converting of `TaggedTemplateExpressions` to the `es5` code, based on `babel` logic.
Still don't sure that i want to merge this, obfuscator should obfuscate code, not transpile it.
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/719
