### ISSUE TITLE
Absolute path as parameters

### ISSUE THREAD

**Issue by isaelblais** [javascript-obfuscator/javascript-obfuscator#576] opened 2020-03-10 23:59 UTC
Hi,

I don't understand why I call javascript-obfuscator with absolute path and it doesn't work. I call it like this:

javascript-obfuscator C:\NodeJsObfuscate\src --output C:\NodeJsObfuscate\obfuscated

I get the error:  Illegal characters in path. When I pass absolute path a source files, the app get the source correctly and it works, but the absolute path for the --output parameters cause error. What am I doing wrong ? 

Thanks in advance

**Comment by sanex3339** [comment] 2020-03-11 06:32
Hi. I can't test it on the `Windows`, so maybe someone other can help you.

**Comment by sanex3339** [comment] 2020-03-13 08:34
Anyone can investigate this?

**Comment by xiaoyijun** [comment] 2020-03-14 00:42
maybe you can try
`javascript-obfuscator C:\\NodeJsObfuscate\\src --output C:\\NodeJsObfuscate\\obfuscated`

**Comment by sanex3339** [comment] 2020-05-26 20:37
Hi. Any news?

**Comment by da411d** [comment] 2020-07-01 22:54
First, i used to think that is because of exception in `mkdirp` package, caused by [path-arg.js:17](https://github.com/isaacs/node-mkdirp/blob/master/lib/path-arg.js#L17)
But then i checked it separately and it worked fine. 

Then i added some `console.log` to `/node_modules/javascript-obfuscator/node_modules/mkdirp/lib/path-arg.js` and what i get that `path` (`pathArg` function argument) equals... `D:\_PROJECTS\_WEB\test\result\D:\_PROJECTS\_WEB\test\src`
And then `mkdirp` causes exception because of illegal `:` in path!

Soooo:
**My command:**
`javascript-obfuscator D:\_PROJECTS\_WEB\test\src --output D:\_PROJECTS\_WEB\test\result`

**Expected result path:**
`D:\_PROJECTS\_WEB\test\result`

**Actual result path:**
`D:\_PROJECTS\_WEB\test\result\D:\_PROJECTS\_WEB\test\src`


I think bug is in function `getOutputCodePath` in [cli/utils/ObfuscatedCodeWriter.ts:38](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/79d639feb6e9ea2fa29baa3ea0c70ad15118ed86/src/cli/utils/ObfuscatedCodeWriter.ts#L38)

**Comment by gaurav-cointab** [comment] 2020-08-20 12:32
This we have also faced. Has this been addressed? @sanex3339

**Comment by sanex3339** [comment] 2020-08-30 17:46
PR welcomed

**Comment by sanex3339** [comment] 2020-10-07 10:58
Anybody can test this PR:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/772 ?

**Comment by sanex3339** [comment] 2020-10-08 03:41
Merged to the `master` branch. I'll release a new version soon.

**Comment by sanex3339** [comment] 2020-10-08 19:15
Released as `2.5.0`

**Closed by sanex3339** 2020-10-08 19:15 UTC
Labels: help wanted, question
