### ISSUE TITLE
Global variables introduced by obfuscator

### ISSUE THREAD

**Issue by dcoliv** [javascript-obfuscator/javascript-obfuscator#170] opened 2018-01-10 15:29 UTC
First of all, congratulations! This is a great project!

I've noticed that enabling some of the obfuscator features (e.g. "stringArray") causes variables to be placed in the global namespace of the obfuscated code.
This is a problem if we import, for instance, two obfuscated JS files into a web page (or if some other imported 3rd party lib also publishes a variable with the same name).
Both generated files would contain a global declaration similar to "var a = [<string array>];", which would cause the second one to override the first declared one.

We've managed to find a workaround for this, which is to wrap the obfuscated code inside an IIFE, and it works. The problem is that the source map that the obfuscator generates does no longer work for that file, because the obfuscated code has been changed (with the IIFE).
Which is a pity... currently I had to disable the source maps just because of this "detail".

Could this be fixed in a near future, or is there something I can do to overcome this problem?
Thanks in advance.

**Comment by sanex3339** [comment] 2018-01-10 15:34
I'll think about option like `wrapCode`. But for example in other projects like `uglify.js`, the same problem will exist.

**Comment by slig** [comment] 2018-01-10 15:55
> But for example in other projects like uglify.js, the same problem will exist.

I believe the issue is a code like this has zero global variables:

```
(function() { 
  function hi() {
  	console.log("Hello World!");
  }
  hi()
})()
```

But after obfuscation it now has 2 global variables: `a` and `b`:

```
var a = [
    '\x6c\x6f\x67',
    '\x48\x65\x6c\x6c\x6f\x20\x57\x6f\x72\x6c\x64\x21'
];
var b = function (c, d) {
    c = c - 0x0;
    var e = a[c];
    return e;
};
(function () {
    function c() {
        console[b('0x0')](b('0x1'));
    }
}());
```

**Comment by sanex3339** [comment] 2018-01-10 15:58
Ah, true.

**Comment by sanex3339** [comment] 2018-01-10 15:59
Anyway, new option seems resoanable.

**Comment by dcoliv** [comment] 2018-01-10 16:01
Exactly @slig. That's exactly our case.
A new option for us would do.
Thanks!

**Comment by sanex3339** [comment] 2018-01-10 16:04
Also this is nice fit use new `finalizing` transformers section, that i implemented in PR with `eval` obfuscation.

https://github.com/javascript-obfuscator/javascript-obfuscator/pull/169/files#diff-d2e2508047c24e24bfd9bde17a6f0928R68

**Comment by india081947** [comment] 2018-01-16 08:07
Hello, @sanex3339 , Really fantastic project.

As mentioned by @dcoliv i would like to bring in your notice that we recently put the obfuscated code in our beta product, and found that it was throwing following error:

Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Function._0x0a9e.base64DecodeUnicode (<anonymous>:1:2825)
    at _0x0a9e (<anonymous>:1:3886)
    at Object.initForm (<anonymous>:1:58310)
    at <anonymous>:1:33240
    at <anonymous>

Above error has come due to conflict in same global variable being declared in different file. So it is not the only problem with other third party library having same global variable but where in our case we have hundreds of file being obfuscated, and found that many of that file has generated same global variable and due to that we had to immediately take the obfuscated code down as it has started throwing above errors.

It may possible that there might be an workaround in the project but unfortunately I did not found. 

It would be great if we can get the following options:

1. Whether to generate common functions like base64DecodeUnicode, cookie functions and other common function across all obfuscated file in a same file or create a new file with filename as input, so that it will save some space instead duplicating all those same code in all the file. if the options is given not to generate common function then it will skip generating common function and developer will import common functions before using obfuscated file.

2. Global Variable Prefix Input, If specified then it will prefix all the global variable with that prefix to avoid being duplicated with other conflicting library. So **var a** will become **var #prefix#_a** and same in case of hexadecimal. 

This will also **resolve a problem of duplicate** variable being generated for same project as now we will pass prefix as **project prefix + file prefix**, so if we have project calculator with file name common.js, we will pass prefix something like calc_common or calc_1 and finally obfuscated file will have variable like **var calc_common_a** or **calc_1_a** and we can differential all the global variable by project and file name. And this way we might not need to wrap around as mentioned by @dcoliv. 

We used this options:  --string-array-encoding base64 --unicode-escape-sequence true string-array-threshold 1 --identifier-names-generator mangled --self-defending true --seed 145

Where we have also tried passing different seeds to every file.

It would be great if we can have this feature.

Thanks

**Comment by sanex3339** [comment] 2018-01-16 08:57
Looks like `identifiersPrefix` option will good for both cases.

**Comment by india081947** [comment] 2018-01-16 09:29
Thanks for expeditious revert,, as mentioned `identifiersPrefix ` can be the best option, webpack need to be analyzed.

**Comment by india081947** [comment] 2018-01-17 10:25
Hi,

I have made some changes to handle something like `identifiersPrefix`, in following files and it seems working for hexadecimal. I am not sure where else it may have impact but as we tested, its working fine.

**src/cli/JavaScriptObfuscatorCLI.ts Line: 320**
`.option(
                '--identifiers-prefix <string>',
                'Sets identifiers prefix'
            )`

**src/interfaces/options/IOptions.d.ts: Line 34**
`    readonly identifiersPrefix: string;`

**src/options/Options.ts: Line 221**
`   /**
     * @type {string}
     */
    @IsString()
    @ValidateIf((options: IOptions) => Boolean(options.identifiersPrefix))
    public readonly identifiersPrefix: string;
`

**src/options/presets/Default.ts Line: 34**
`unicodeEscapeSequence: false,
    identifiersPrefix: ''`

**src/generators/identifier-names-generators/HexadecimalIdentifierNamesGenerator.ts Line: 38**
`const randomVariableName: string = `${this.options.identifiersPrefix}` + `${prefix}${hexadecimalNumber.substr(0, length)}` ;`

Additional other test case validation and check may require.

@sanex3339, It would be great if something can be integrated. And also, Please excuse me as these are my initial posts in Github and to this repository. 

Thanks

**Comment by sanex3339** [comment] 2018-01-17 11:19
Yeah, i'll do something like this today or tomorrow.
But here `${this.options.identifiersPrefix}+${prefix}${hexadecimalNumber.substr(0, length)};`
I'll will do this
```
${this.options.identifiersPrefix || prefix}${hexadecimalNumber.substr(0, length)};
```

**Comment by india081947** [comment] 2018-01-17 12:02
Seems that's also a good Idea. Thanks a lot!

**Comment by sanex3339** [comment] 2018-01-17 22:48
Base realisation in this PR
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/180/files

But here one big TODO - i should do something with directory obfuscation via CLI.
Random prefix that will generated inside CLI class when directory obfuscation is enabled - solution. But what if prefix already was set? Should i use it for all obfuscated files or replace it by random prefix for each file?

**Comment by india081947** [comment] 2018-01-18 06:20
Hi @sanex3339, First Thanks for taking this requirement and completing it.

For directory obfuscation, As far as I know, We already use random generator for variable name generation but still it won't be guaranteed that it wont duplicate, as in even hundred js files it has duplicated the hexadecimal name.

Scenario 1:  Single directory recursive generation - This may go through as it may wont let repeat the number as it is being cached and it is single CLI session

Scenario 2: If I have 5 different directories and from CLI, I am calling recursive obfuscation on directory, it may possible that it can generator same global variable name again. This is session less / stateless utility and it wont be able to keep a track of what global variable was generated in prev session and chances are to get it repeated.

Directory obfuscation should be left at user side as it will any way take 1 more line of coding as mentioned below.

```
set /A seed = 1
for %%i in (ui\js\dir1\*.js) do ( set /A seed = seed + 1 & call obfuscat.bat %%i %%seed%%)
for %%i in (ui\js\dir2\*.js) do ( set /A seed = seed + 1 & call obfuscat.bat %%i %%seed%%)
```
In above code obfuscat.bat has following arguments:

`--string-array-encoding base64 --unicode-escape-sequence true string-array-threshold 1 --identifier-names-generator hexadecimal --self-defending true --seed %2 --identifiers-prefix project1_%2`

This way it will ensure that seed / file counter will be incremented in each call which will be prefixed with global variable to make it guaranteed unique. Here I am using seed for both purpose 1) seed 2) file prefix.


P.S.: 
1) In Read me, I think you might not wanted to specify only mangled option. >> Use this option when `identifierNamesGenerator: 'mangled'` 
2) I hope you dont want prefix track in this.previousMangledName = newName;

**Comment by india081947** [comment] 2018-01-18 09:09
> About directory obfuscation:
> CLI already has this feature and this feature should work without external scripts. So, i'll think about how to handle it, but right now as i see - the only way is to rewrite prefix to the random one.

It should work without problem, as identifiersPrefix will be anyway passed to the the obfuscation process at `JavaScriptObfuscatorCLI.processSourceCode` and it will be prefixed. If random has to be generated then you might need to shift `const options: TInputOptions = this.buildOptions();` from function `JavaScriptObfuscatorCLI.processSourceCode` and has to be passed after altering the identifiersPrefix with `identifiersPrefix  + getRandomeNumber()` in the function `processSourceCodeData` > else condition within forEach

Unfortunately directory  obfuscation is not working in my Windows Machine `(RangeError: Maximum call stack size exceeded at Object.fs.mkdirSync (fs.js:924:18))` otherwise I would have tested and sent the actual code snippet of above changes. Please do check if that way it can be done.

**Comment by sanex3339** [comment] 2018-01-18 22:40
So. The logic will be following:
* it option value is not empty string - prefix will be as this string
* if option value is `true` (boolean) - prefix will be as random string with length of 3 characters
* if option value is `false` (boolean) or an empty string - no prefix

**Comment by sanex3339** [comment] 2018-01-18 22:56
I updated PR

**Comment by india081947** [comment] 2018-01-19 05:59
@sanex3339,  I have updated review, please check..

On directory I would suggest, please use private static global counter for internal prefix for next file in directory, instead random number to be 100% sure of no duplicate.

**Comment by sanex3339** [comment] 2018-01-24 14:58
Merged into master.
`identifiersPrefix` option. Empty string (default) - no prefix.
For directory obfuscation with CLI - index of the file will added to the prefix (`foo0`, `foo1`); or if prefix is empty - prefix will set to `a` + index (`a0`,`a1`)

**Comment by sanex3339** [comment] 2018-01-24 17:05
`javascript-obfuscator@0.14.0-beta.3` was published to npm

**Comment by india081947** [comment] 2018-01-25 04:54
@sanex3339, it was like show-stopper, really awesome work done.   
Thanks!

**Comment by sanex3339** [comment] 2018-01-28 11:09
Hi, did you test it? Everything is ok?

**Comment by india081947** [comment] 2018-01-29 08:59
@sanex3339, We tested it and we did not find any problem.. It has generated all unique variable at first sight, thorough testing is scheduled next month but so far no problem all seems good.
Thanks so much!

**Comment by sanex3339** [comment] 2018-02-04 19:17
out in `javascript-obfuscator@0.14.0`

**Closed by sanex3339** 2018-02-04 19:17 UTC
Labels: enhancement, fixed, waiting for release

**Comment by ShaulTransmit** [comment] 2023-02-05 15:54
I have encountered similar situation and am wondering if using `identifiersPrefix` still the recommended solution?

at the top of the discussion there's a mention of adding "wrapCode" functionality that will wrap all in an iife, that approach seem safer, as even with prefix, 2 scripts might define the same prefix.

Should I open a new issue for that?

**Comment by ibreathebsb** [comment] 2023-07-13 01:32
I think prefix won't sovle all problems,maybe IIFE is a better solution
