### ISSUE TITLE
Wrong obfuscation that make a runtime error

### ISSUE THREAD

**Issue by shkedi** [javascript-obfuscator/javascript-obfuscator#496] opened 2020-01-13 21:56 UTC
I have in my code before the obfuscatoion the following line
const requestId = actions.map(({ requestId }) => requestId).find(requestId => requestId);

after the obfuscation, The code look like:
{const _0x50449f=_0x47bbac[_0x2430('0x71')](({requestId})=>_0x50449f)

In the clear code, it is clear that the requestId in the left side (variable definition) is not the same requestId inside the find, but we can see that after the obfuscation the requestId variable (in the left side) has the same address like the requestId in the find. 

This makes an error: ReferenceError: _0x50449f is not defined

**Comment by sanex3339** [comment] 2020-01-13 22:00
Can reproduce with the following code:
```
(function () {
    const actions = [
      {
          someAction: 'foo'
      }, 
      {
          requestId: 123
      }
    ];
    const requestId = actions.map(({ requestId }) => requestId).find(requestId => requestId);
    console.log(requestId);
})();
```

**Comment by sanex3339** [comment] 2020-01-13 22:32
Minimal code to reproduce
```
const foo = [].map(({ foo }) => foo);
```

when `renameGlobals` is enabled

**Comment by sanex3339** [comment] 2020-01-13 22:50
I think I need to completely rework how variables are renamed because the current approach is very buggy and hard to maintain

**Comment by shkedi** [comment] 2020-01-14 05:50
Thanks for your quick response. Waiting for the fix.

**Comment by sanex3339** [comment] 2020-01-18 08:41
Hi, can you test this PR and branch?
`eslint-scope`
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/503

**Comment by sanex3339** [comment] 2020-01-18 22:09
Hi. Expect a new release in a few days. Maybe tomorrow.

**Comment by shkedi** [comment] 2020-01-21 07:17
I saw was a new release, 0.23.2.
With this version, the issue still reproduces.

**Comment by sanex3339** [comment] 2020-01-21 09:29
This issue will fixed in `0.24.0`

**Comment by sanex3339** [comment] 2020-01-26 21:41
Released as `0.24.0`

**Comment by shkedi** [comment] 2020-01-26 22:10
Thanks, I will check it out and let you know

**Comment by shkedi** [comment] 2020-01-30 14:15
I checked version 0.24.1. the error doesn't appear, but some tests in our CI/DC failed (without an exception in our log)

**Comment by sanex3339** [comment] 2020-01-30 14:18
Try 0.24.3 version, it contains bugfix with class expressions.
Also, if you are using exponentiation operator `**`, replase it on Math.pow, because of 
https://github.com/javascript-obfuscator/javascript-obfuscator/issues

**Comment by shkedi** [comment] 2020-01-30 14:37
Thanks for your quick response.
Unfortunately, some tests still fail in this (0.24.3) version

**Comment by sanex3339** [comment] 2020-01-30 14:38
So, here isn't any log about failing tests?

**Comment by shkedi** [comment] 2020-01-30 14:40
The test fails because of an unexcepted result, but there isn't a javascript error or error that was written by a developer

**Comment by shkedi** [comment] 2020-01-30 20:39
I have the app's logs, but I didnt see a special exception in the log. As I
said, some tests fails, and without the obfuscation they didn't

**Comment by sanex3339** [comment] 2020-01-30 20:49
Not enough info. Need something more to understand what is the problem.
Show me your options.

**Comment by shkedi** [comment] 2020-01-30 21:01
I really understand u, but as I see it, it looks that the version not
stable and I am afraid to upgrade my app with your moduke's latest version.
My app in production and in case of bug it will be a disaster. I know it
difficult without my investagtion.

**Comment by sanex3339** [comment] 2020-01-30 21:11
Errors are consistent and appear every time?
Errors are appeared with any options or with a specific ones?

**Comment by shkedi** [comment] 2020-01-30 22:12
I don't see error in the log, but my test is failing with a wrong results

**Comment by sanex3339** [comment] 2020-01-31 06:07
So, I need from you:
- obfuscation options and more info about it. Will errors appear with minimum obfuscation options?
-  this test fails are constant or not?

**Comment by shkedi** [comment] 2020-01-31 06:19
I am not using any option (using default)
Same test failing all the time.

If do you want, we can schedule a zoom meeting and I will show you the
issue.

**Comment by sanex3339** [comment] 2020-02-03 10:45
Try to set `shuffleStringArray: false`. Will it help?

**Comment by sanex3339** [comment] 2020-02-04 22:21
Please, try 0.24.5 version

**Closed** 2020-02-04 22:23 UTC
Labels: bug

**Comment by shkedi** [comment] 2020-02-05 09:13
Thanks again. I tried the latest version (0.24.5). The problematic test passed. hope my CI passes as well and I can move to this version.

**Comment by sanex3339** [comment] 2020-02-05 09:15
Nice!

**Comment by shkedi** [comment] 2020-02-05 12:15
Working, move to this version.  thanks :)
