### ISSUE TITLE
ReferenceError: Given config path must be a valid file path

### ISSUE THREAD

**Issue by sido420** [javascript-obfuscator/javascript-obfuscator#190] opened 2018-02-10 19:03 UTC
Not sure what mistake I'm making but I've tried giving it relative (to curr working dir), absolute, and input file dir. However, it keeps throwing this error.

The contents are copy and paste of all possible params in Readme.

```
cd /text

./node_modules/javascript-obfuscator/bin/javascript-obfuscator ./tmp/js.merged.js --config obfuscator.js 

/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/utils/CLIUtils.ts:58
                throw new ReferenceError('Given config path must be a valid file path');
                      ^
ReferenceError: Given config path must be a valid file path
    at Function.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/utils/CLIUtils.ts:58:23)
    at e.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/JavaScriptObfuscatorCLI.ts:178:93)
    at e.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/JavaScriptObfuscatorCLI.ts:376:58)
    at e.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/JavaScriptObfuscatorCLI.ts:354:35)
    at e.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/cli/JavaScriptObfuscatorCLI.ts:168:35)
    at Function.value (/text/node_modules/javascript-obfuscator/dist/webpack:/src/JavaScriptObfuscatorFacade.ts:42:5)
    at Object.<anonymous> (/text/node_modules/javascript-obfuscator/bin/javascript-obfuscator:3:26)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
```
also,

```
cat ./obfuscator.js 
{
    compact: true,
    controlFlowFlattening: false,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: false,
    deadCodeInjectionThreshold: 0.4,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    domainLock: [],
    identifierNamesGenerator: 'hexadecimal',
    identifiersPrefix: '',
    log: false,
    renameGlobals: false,
    reservedNames: [],
    rotateStringArray: true,
    seed: 0,
    selfDefending: false,
    sourceMap: false,
    sourceMapBaseUrl: '',
    sourceMapFileName: '',
    sourceMapMode: 'separate',
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    target: 'browser',
    transformObjectKeys: false,
    unicodeEscapeSequence: false
}
```

**Comment by sanex3339** [comment] 2018-02-10 20:01
In the code it just trying to require config by given path. Your js file with config looks like not a valid javascript code. Change file extension to json or keep js extension but export config object via
`module.exports = {};`

**Comment by sido420** [comment] 2018-02-10 20:33
Thanks. 

I had copied and pasted the exact config you have in Readme. But, you were right, adding module.exports = {...} resolved it.

**Comment by sanex3339** [comment] 2018-02-10 21:25
In a future release i will update error message on
```
Given config path must be a valid path of `.js` or `.json` file
```

**Comment by AlLoud** [comment] 2018-02-15 12:18
I'm having this same issue, but I'm using a script in my _package.json_ which is invoking the config in the following way:

    "obfuscate": "javascript-obfuscator js/stuff.js --config js/config.json"

I'm running it through:

   npm run obfuscate

In the root of my project. I have tried to add quotes to the config path `--config \"js/config.json\", and also a reference to the current folder `--config ./js/config.json` and to place it in the root folder. 
I have also tried to running it directly through node (similar to sido420 command), to use the default options and emptying the _config.json_, none of these work.

It only works when:
- I don't use the `--config` parameter OR
- the `conf.json` file is an empty object `{}`

The moment I add something (e.g. `{compact: true}`), the _ReferenceError_ shows up. So it seems to me there's something else when the JSON is being parsed.

I'm not sure if the suggested `module.exports` solution is just pasting `module.exports = ` right before the opening bracket in the _config.json_ (which is also not working for me).
If this variable should be assigned somewhere else, can you detail where to do it in this context?

**Comment by AlLoud** [comment] 2018-02-15 12:25
Thanks for the quick response. I have tried:

    {compact: "true"}

Or:

    {compact: true}

Or:

    {
      'compact': true
    }

Or the default options:

{
    compact: true,
    controlFlowFlattening: false,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: false,
    deadCodeInjectionThreshold: 0.4,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    domainLock: [],
    identifierNamesGenerator: 'hexadecimal',
    identifiersPrefix: '',
    log: false,
    renameGlobals: false,
    reservedNames: [],
    rotateStringArray: true,
    seed: 0,
    selfDefending: false,
    sourceMap: false,
    sourceMapBaseUrl: '',
    sourceMapFileName: '',
    sourceMapMode: 'separate',
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    target: 'browser',
    transformObjectKeys: false,
    unicodeEscapeSequence: false
}

The only _config.json_ content that worked until now was `{}` or:

    {
    }

I'm using node version 9.2.1.

**Comment by AlLoud** [comment] 2018-02-15 12:38
Alright, I got it working this way:

    {
      module.exports = {
        compact: true
      }
    }

So the `module.exports` must be a property of the larger object.

**Comment by sanex3339** [comment] 2018-02-15 12:38
Wow, it's very strange.

**Comment by sanex3339** [comment] 2018-02-15 12:39
I'll check it.

**Comment by sanex3339** [comment] 2018-02-18 10:08
I updated tests but can't reproduce your bug
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/199

**Comment by AlLoud** [comment] 2018-02-19 10:12
Thank you @sanex3339 . I updated to v0.14.3 and I noticed that in the new _est/fixtures/config.json_ you added you used double quotes (`"` instead of `'`). Since I'm running on Windows, I remembered that bash always expects double quotes in all strings, so when I **replaced all single quotes by double quotes and also added double quotes to all properties names**, it finally worked! Now it reads directly from a normal _.js_ or _.json_ file (in any path). So the default options for Windows users would be instead:

    {
      "compact": true,
      "controlFlowFlattening": false,
      "controlFlowFlatteningThreshold": 0.75,
      "deadCodeInjection": false,
      "deadCodeInjectionThreshold": 0.4,
      "debugProtection": false,
      "debugProtectionInterval": false,
      "disableConsoleOutput": false,
      "domainLock": [],
      "identifierNamesGenerator": "hexadecimal",
      "identifiersPrefix": "",
      "log": false,
      "renameGlobals": false,
      "reservedNames": [],
      "rotateStringArray": true,
      "seed": 0,
      "selfDefending": false,
      "sourceMap": false,
      "sourceMapBaseUrl": "",
      "sourceMapFileName": "",
      "sourceMapMode": "separate",
      "stringArray": true,
      "stringArrayEncoding": false,
      "stringArrayThreshold": 0.75,
      "target": "browser",
      "transformObjectKeys": false,
      "unicodeEscapeSequence": false
    }

And a typical run command could be:

    javascript-obfuscator js/stuff.js --config js/obfuscator.json


Notes
---

1. When the config file has a different extension, it's still possible to use the `module.exports` assignment with single quotes (in Windows), i.e. if you have a file name `.jsobfuscatorrc` with this content:

    {
      module.exports = {
        compact: true
        identifierNamesGenerator: 'hexadecimal',
      }
    }

This is working as well:

    javascript-obfuscator js/stuff.js --config js/.jsobfuscatorrc

Since I set up several different folders this way, for now I might just keep using it like this.

2. However, when something fails, the ReferenceError output now is huge (with lots of new lines before the code): https://gist.github.com/AlLoud/e0a5f6bc3c957635f7fe031686cc89b1 (not sure if this is on purpose but sometimes it doesn't clear out from the bash).

**Comment by sanex3339** [comment] 2018-02-19 22:41
> However, when something fails, the ReferenceError output now is huge (with lots of new lines before the code)

How i can reproduce this?
My output is following:

```
/Users/sanex/PhpstormProjects/javascript-obfuscator/dist/webpack:/src/cli/utils/CLIUtils.ts:58
                throw new ReferenceError('Given config path must be a valid `.js` or `.json` file path');
                      ^
ReferenceError: Given config path must be a valid `.js` or `.json` file path
```

**Comment by AlLoud** [comment] 2018-02-20 09:56
Sorry @sanex3339 I can only suggest to run it in a windows shell for debugging it. I also upgraded to the latest node version (9.5.0) and the same output comes out when the config is not found.
Thank you so far, it's been awesome!

**Comment by sanex3339** [comment] 2018-02-20 20:16
Closed as resolved

**Closed by sanex3339** 2018-02-20 20:16 UTC
Labels: question
