### ISSUE TITLE
Can support static member in class?

### ISSUE THREAD

**Issue by jianweiqin** [javascript-obfuscator/javascript-obfuscator#815] opened 2020-11-19 01:34 UTC
I was obfuscating the code below:
>class A {
>	static list = [];
> }

but got an error:
>Error: ERROR at line 3: Unexpected token (3:13)
>...static list = [];...

Can support static member in class?

## Your Environment

* Obfuscator version used:2.9.1
* Node version used:14.8

# Stack trace
>        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
>              ^
>Error: ERROR at line 3: Unexpected token (3:13)
> ...static list = [];...
    at Function.processParsingError (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67:15)
    at Function.parse (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:39:49)
    at o.parseCode (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:81:50)
    at obfuscate (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:72:30)
    at Function.obfuscate (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscatorFacade.ts:16:53
)
    at P.apply (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:197:82)
    at P.processSourceCodeWithoutSourceMap (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initial
izable.ts:61:39)
    at P.apply (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:193:18)
    at P.processSourceCode (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:61:39)
    at C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:177:22

**Comment by sanex3339** [comment] 2020-11-19 04:10
Duplicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/510

**Closed by sanex3339** 2020-11-19 04:10 UTC
