### ISSUE TITLE
"Numbers to expressions" incorrect for small numbers

### ISSUE THREAD

**Issue by PFPF** [javascript-obfuscator/javascript-obfuscator#882] opened 2021-02-18 22:18 UTC
A little confused that my obfuscated code worked differently than the original code, then I found that it's the "numbers to expressions" misbehaving.

## Current Behavior
"Numbers to expressions" option loses accuracy for small numbers, turning them into 0.

## Steps to Reproduce
1. `const epsilon = 1e-13; if(0 < epsilon) alert("math works!");`
2. [Obfuscate](//obfuscator.io) with "numbers to expressions" option on
3. Math doesn't work :(

It'll be great if this feature can be made more robust. I haven't looked at the implementation code, but I guess you can do something like the following:
1. For any number x, extract its integer and decimal part
2. Obfuscate the integer part as what you would do
3. Generate a random integer n between 100 and 100000, and obfuscate the decimal part d as [result of d * n] / n (maybe even obfuscate n as what you would do)
4. add 'em up

**Comment by BlackYuzia** [comment] 2021-02-19 08:37
@sanex3339 did you fix anything in obfuscator.io?

Because I try obfuscate this:
```js
const epsilon = 1e-13; if(0 < epsilon) alert("math works!");
```
and I get `math works!` result.

I use numbers to expression option.

**Comment by sanex3339** [comment] 2021-02-19 08:39
No, i haven't fixed anything yet.
Right now i'm thinking about the solution but looks like the easiest way is to convert only integer numbers

**Comment by PFPF** [comment] 2021-02-19 09:42
@BlackYuzia I think "math works!" iff the last randomized term is < 1024 (because 1024 is the smallest number such that `1024 + 1e-13 == 1024`) lol

@sanex3339 Looking forward to it. What do you think about the method I mentioned? So for 1e-13, you would get something like `const epsilon = -0x2551+0x12*0x219+-0x71+1.2434e-9/(-0x1*0x149f+-0x1b27*-0x2+0xee3)`. I think it should be robust and easy, since you can just wrap around the current mechanism.

**Comment by sanex3339** [comment] 2021-02-22 13:32
Ok. I will implement @PFPF approach.

**Comment by sanex3339** [comment] 2021-02-23 09:51
Hmm.
The problem is that even with the suggested approach the resulting number may be different from the input value.
For `1e-13` the output expression is `-0xa9*-0x29+-0x1df*0xe+-0xdf+(-0xcb6+0x2335*-0x1+12267.00000000686)/0x10be9;` and this expression does not match to the input number.

As a simple solution, I can disable transformation of all float numbers.

**Comment by PFPF** [comment] 2021-02-23 16:08
Oh, I think we are obfuscating the denominator (integer) not the numerator (decimal)?

**Comment by sanex3339** [comment] 2021-02-23 21:10
PR:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/885

**Comment by PFPF** [comment] 2021-02-24 01:29
Thanks for the swift response. Could you confirm that it works with -1e-20 too?

**Comment by sanex3339** [comment] 2021-02-25 11:52
Merged
Will release it later today

**Comment by PFPF** [comment] 2021-02-25 11:57
Looks good!

**Closed** 2021-02-25 11:58 UTC
Labels: bug, high priority

**Comment by sanex3339** [comment] 2021-02-25 14:25
Released as 2.10.4

**Comment by PFPF** [comment] 2021-02-25 16:19
Great. For better obfuscation purpose, I would still suggest having a random, obfuscated integer as the denominator of the decimal part, but the current implementation does fix the issue. Thx for your time on this!

**Comment by BlackYuzia** [comment] 2021-02-25 20:37
![image](https://user-images.githubusercontent.com/25010528/109214003-f94a8e00-77b9-11eb-93b7-0e26147d4e20.png)
То чувство когда случайно включил гуглпереводчик. Но он сделал все только прекраснее.
