### ISSUE TITLE
`process.env` is empty

### ISSUE THREAD

**Issue by elyran** [javascript-obfuscator/javascript-obfuscator#863] opened 2021-01-18 19:38 UTC
`process.env` is empty.
I'm using the `webpack-obfuscator` addon.
On the `low-obfuscation` preset `process.env` is NOT empty.

At first I thought the error is in `webpack-obfuscator`, but if it works on `low-obfuscation` preset, then we can safely conclude the error isn't there, but in `javascript-obfuscator`.

## Expected Behavior
`process.env` has values.

## Current Behavior
`process.env` is empty.

## Steps to Reproduce

Please see the code example.

## Your Environment

* Obfuscator version used:
```
    "javascript-obfuscator": "^2.10.1",
    "webpack-obfuscator": "^3.2.0"
```
* Node version used: 12 LTS

# Stack trace

## Minimal working example that will help to reproduce issue

Project created with `create-react-app`, Webpack hacked with `react-app-rewired`.

Webpack:

```
    config['module']['rules'].push({
      test: /src\/.*\.js$/,
      enforce: 'post',
      use: {
        loader: WebpackObfuscator.loader,

        options: {
            // optionsPreset: 'low-obfuscation', // Works fine.
            optionsPreset: 'medium-obfuscation', // Fails. `process.env` is empty.
          }
      }
    })
```

index.js:

Replace content with this:

```
console.log('--- start')
console.log('process.env:', process.env)
console.log('--- end')
```

To run:
`REACT_APP_XYZ=123 yarn build`

Now, again, on the `low-obfuscation` preset it works. `process.env` is NOT empty.
But on the `medium-obfuscation` preset it's empty.

**Comment by elyran** [comment] 2021-01-18 19:43
I also tried using `reservedNames`:
```
            reservedNames: [
              'process',
              'process\.env',
              'REACT_APP_XYZ',
            ],
```

**Comment by sanex3339** [comment] 2021-01-23 16:40
Can you create a repo with a reproducible example?

**Comment by sanex3339** [comment] 2021-02-03 20:35
Please try the latest `webpack-obfuscator@3.3.0`

**Comment by sanex3339** [comment] 2021-02-28 19:35
Closed as old. Write here if this issue still happens.

**Closed by sanex3339** 2021-02-28 19:35 UTC
Labels: need more info

**Comment by JanCusters** [comment] 2021-03-22 16:44
Same problem here, even on the latest build

**Comment by JanCusters** [comment] 2021-03-22 16:49
@elyran did you manage to fix it?

**Comment by Katarn** [comment] 2021-08-03 21:04
I made a [minimal example](https://github.com/Katarn/obfuscator-process-bug).

Just run `npm ci && npm run build`. After that, in the `dist` directory, you will see the `main.js` file. Open it in a code editor and you will see something like:

```js
....shift())}}(n),process[r(309)][r(311)]&&console[r(302)](r(311))})();...
```

Of course, the `process` variable is `undefined`. Moreover, it should not be in the code, it should either be replaced with `true` (according to [this line](https://github.com/Katarn/obfuscator-process-bug/blob/master/webpack.config.js#L22)), or, with "smart optimization", the `if (...)` check block should not exist at all, since it will always be executed.

Then you can uncomment these [two lines](https://github.com/Katarn/obfuscator-process-bug/blob/5edcd56c5f2f18b6068e8459f7be075fc9691bb5/webpack.config.js#L14-L15) (not necessarily at the same time, you can uncomment them separately) and see how the code is generated in the `main.js` file.

**Comment by thierrymichel** [comment] 2021-10-04 10:18
This is how I fixed it:
```js
/* javascript-obfuscator:disable */
const endpoint = `${process.env.VUE_APP_API_DOMAIN}/api/v1`
/* javascript-obfuscator:enable */
